// flow-typed signature: e66ce721b151447b61a596858127e3b6
// flow-typed version: <<STUB>>/babel-plugin-transform-react-flow-handled-props_v^0.1.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-flow-handled-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-flow-handled-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-flow-handled-props/lib/assertions' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/appendProps' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/createExpressions' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getClassDeclaration' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getEntryIdentifier' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getExpressionIdentifier' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getVariableDeclarator' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/isReactComponent' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/isReactImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/Store' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/types' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/entryVisitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/importVisitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/propVisitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/assertions' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/appendProps' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/createExpressions' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getClassDeclaration' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getEntryIdentifier' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getExpressionIdentifier' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getVariableDeclarator' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/isReactComponent' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/isReactImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/Store' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/util/types' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/entryVisitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/importVisitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/propVisitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-flow-handled-props/lib/assertions.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/assertions'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/appendProps.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/appendProps'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/createExpressions.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/createExpressions'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getClassDeclaration.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/getClassDeclaration'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getEntryIdentifier.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/getEntryIdentifier'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getExpressionIdentifier.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/getExpressionIdentifier'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/getVariableDeclarator.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/getVariableDeclarator'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/isReactComponent.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/isReactComponent'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/isReactImport.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/isReactImport'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/Store.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/Store'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/util/types.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/util/types'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/entryVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/visitors/entryVisitor'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/importVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/visitors/importVisitor'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/visitors/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/lib/visitors/propVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/lib/visitors/propVisitor'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/assertions.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/assertions'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/appendProps.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/appendProps'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/createExpressions.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/createExpressions'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getClassDeclaration.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/getClassDeclaration'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getEntryIdentifier.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/getEntryIdentifier'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getExpressionIdentifier.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/getExpressionIdentifier'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/getVariableDeclarator.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/getVariableDeclarator'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/isReactComponent.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/isReactComponent'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/isReactImport.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/isReactImport'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/Store.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/Store'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/util/types.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/util/types'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/entryVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/visitors/entryVisitor'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/importVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/visitors/importVisitor'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/visitors/index'>;
}
declare module 'babel-plugin-transform-react-flow-handled-props/src/visitors/propVisitor.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-flow-handled-props/src/visitors/propVisitor'>;
}
