// flow-typed signature: 3dcbeebb1d7c09a25cd94608b20dfdc1
// flow-typed version: <<STUB>>/babel-plugin-transform-dev_v^2.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-dev/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-dev/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-dev/lib/index'>;
}
