// flow-typed signature: 5be0f30b912ea3f323bedba34b571f69
// flow-typed version: <<STUB>>/brfs_v^1.6.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brfs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brfs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brfs/bin/cmd' {
  declare module.exports: any;
}

declare module 'brfs/example/async' {
  declare module.exports: any;
}

declare module 'brfs/example/main' {
  declare module.exports: any;
}

declare module 'brfs/test/ag' {
  declare module.exports: any;
}

declare module 'brfs/test/async' {
  declare module.exports: any;
}

declare module 'brfs/test/buffer' {
  declare module.exports: any;
}

declare module 'brfs/test/bundle' {
  declare module.exports: any;
}

declare module 'brfs/test/cmd' {
  declare module.exports: any;
}

declare module 'brfs/test/dynamic_read_concat' {
  declare module.exports: any;
}

declare module 'brfs/test/dynamic_read_no_concat' {
  declare module.exports: any;
}

declare module 'brfs/test/encoding' {
  declare module.exports: any;
}

declare module 'brfs/test/files/ag' {
  declare module.exports: any;
}

declare module 'brfs/test/files/async_encoding' {
  declare module.exports: any;
}

declare module 'brfs/test/files/async_str_encoding' {
  declare module.exports: any;
}

declare module 'brfs/test/files/async' {
  declare module.exports: any;
}

declare module 'brfs/test/files/buffer' {
  declare module.exports: any;
}

declare module 'brfs/test/files/dynamic_read_concat' {
  declare module.exports: any;
}

declare module 'brfs/test/files/dynamic_read_no_concat' {
  declare module.exports: any;
}

declare module 'brfs/test/files/encoding' {
  declare module.exports: any;
}

declare module 'brfs/test/files/hoist' {
  declare module.exports: any;
}

declare module 'brfs/test/files/inline' {
  declare module.exports: any;
}

declare module 'brfs/test/files/main' {
  declare module.exports: any;
}

declare module 'brfs/test/files/multi_var' {
  declare module.exports: any;
}

declare module 'brfs/test/files/non_fs' {
  declare module.exports: any;
}

declare module 'brfs/test/files/path_join_other_name' {
  declare module.exports: any;
}

declare module 'brfs/test/files/path_join_single_var' {
  declare module.exports: any;
}

declare module 'brfs/test/files/path_join' {
  declare module.exports: any;
}

declare module 'brfs/test/files/readdir-sync' {
  declare module.exports: any;
}

declare module 'brfs/test/files/readdir' {
  declare module.exports: any;
}

declare module 'brfs/test/files/separators' {
  declare module.exports: any;
}

declare module 'brfs/test/files/with_comments' {
  declare module.exports: any;
}

declare module 'brfs/test/hoist' {
  declare module.exports: any;
}

declare module 'brfs/test/inline' {
  declare module.exports: any;
}

declare module 'brfs/test/multi_var' {
  declare module.exports: any;
}

declare module 'brfs/test/non_fs' {
  declare module.exports: any;
}

declare module 'brfs/test/path_join_other_name' {
  declare module.exports: any;
}

declare module 'brfs/test/path_join_single_var' {
  declare module.exports: any;
}

declare module 'brfs/test/path_join' {
  declare module.exports: any;
}

declare module 'brfs/test/readdir' {
  declare module.exports: any;
}

declare module 'brfs/test/require_resolve' {
  declare module.exports: any;
}

declare module 'brfs/test/require_resolve/main' {
  declare module.exports: any;
}

declare module 'brfs/test/separators' {
  declare module.exports: any;
}

declare module 'brfs/test/tr' {
  declare module.exports: any;
}

declare module 'brfs/test/with_comments' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brfs/bin/cmd.js' {
  declare module.exports: $Exports<'brfs/bin/cmd'>;
}
declare module 'brfs/example/async.js' {
  declare module.exports: $Exports<'brfs/example/async'>;
}
declare module 'brfs/example/main.js' {
  declare module.exports: $Exports<'brfs/example/main'>;
}
declare module 'brfs/index' {
  declare module.exports: $Exports<'brfs'>;
}
declare module 'brfs/index.js' {
  declare module.exports: $Exports<'brfs'>;
}
declare module 'brfs/test/ag.js' {
  declare module.exports: $Exports<'brfs/test/ag'>;
}
declare module 'brfs/test/async.js' {
  declare module.exports: $Exports<'brfs/test/async'>;
}
declare module 'brfs/test/buffer.js' {
  declare module.exports: $Exports<'brfs/test/buffer'>;
}
declare module 'brfs/test/bundle.js' {
  declare module.exports: $Exports<'brfs/test/bundle'>;
}
declare module 'brfs/test/cmd.js' {
  declare module.exports: $Exports<'brfs/test/cmd'>;
}
declare module 'brfs/test/dynamic_read_concat.js' {
  declare module.exports: $Exports<'brfs/test/dynamic_read_concat'>;
}
declare module 'brfs/test/dynamic_read_no_concat.js' {
  declare module.exports: $Exports<'brfs/test/dynamic_read_no_concat'>;
}
declare module 'brfs/test/encoding.js' {
  declare module.exports: $Exports<'brfs/test/encoding'>;
}
declare module 'brfs/test/files/ag.js' {
  declare module.exports: $Exports<'brfs/test/files/ag'>;
}
declare module 'brfs/test/files/async_encoding.js' {
  declare module.exports: $Exports<'brfs/test/files/async_encoding'>;
}
declare module 'brfs/test/files/async_str_encoding.js' {
  declare module.exports: $Exports<'brfs/test/files/async_str_encoding'>;
}
declare module 'brfs/test/files/async.js' {
  declare module.exports: $Exports<'brfs/test/files/async'>;
}
declare module 'brfs/test/files/buffer.js' {
  declare module.exports: $Exports<'brfs/test/files/buffer'>;
}
declare module 'brfs/test/files/dynamic_read_concat.js' {
  declare module.exports: $Exports<'brfs/test/files/dynamic_read_concat'>;
}
declare module 'brfs/test/files/dynamic_read_no_concat.js' {
  declare module.exports: $Exports<'brfs/test/files/dynamic_read_no_concat'>;
}
declare module 'brfs/test/files/encoding.js' {
  declare module.exports: $Exports<'brfs/test/files/encoding'>;
}
declare module 'brfs/test/files/hoist.js' {
  declare module.exports: $Exports<'brfs/test/files/hoist'>;
}
declare module 'brfs/test/files/inline.js' {
  declare module.exports: $Exports<'brfs/test/files/inline'>;
}
declare module 'brfs/test/files/main.js' {
  declare module.exports: $Exports<'brfs/test/files/main'>;
}
declare module 'brfs/test/files/multi_var.js' {
  declare module.exports: $Exports<'brfs/test/files/multi_var'>;
}
declare module 'brfs/test/files/non_fs.js' {
  declare module.exports: $Exports<'brfs/test/files/non_fs'>;
}
declare module 'brfs/test/files/path_join_other_name.js' {
  declare module.exports: $Exports<'brfs/test/files/path_join_other_name'>;
}
declare module 'brfs/test/files/path_join_single_var.js' {
  declare module.exports: $Exports<'brfs/test/files/path_join_single_var'>;
}
declare module 'brfs/test/files/path_join.js' {
  declare module.exports: $Exports<'brfs/test/files/path_join'>;
}
declare module 'brfs/test/files/readdir-sync.js' {
  declare module.exports: $Exports<'brfs/test/files/readdir-sync'>;
}
declare module 'brfs/test/files/readdir.js' {
  declare module.exports: $Exports<'brfs/test/files/readdir'>;
}
declare module 'brfs/test/files/separators.js' {
  declare module.exports: $Exports<'brfs/test/files/separators'>;
}
declare module 'brfs/test/files/with_comments.js' {
  declare module.exports: $Exports<'brfs/test/files/with_comments'>;
}
declare module 'brfs/test/hoist.js' {
  declare module.exports: $Exports<'brfs/test/hoist'>;
}
declare module 'brfs/test/inline.js' {
  declare module.exports: $Exports<'brfs/test/inline'>;
}
declare module 'brfs/test/multi_var.js' {
  declare module.exports: $Exports<'brfs/test/multi_var'>;
}
declare module 'brfs/test/non_fs.js' {
  declare module.exports: $Exports<'brfs/test/non_fs'>;
}
declare module 'brfs/test/path_join_other_name.js' {
  declare module.exports: $Exports<'brfs/test/path_join_other_name'>;
}
declare module 'brfs/test/path_join_single_var.js' {
  declare module.exports: $Exports<'brfs/test/path_join_single_var'>;
}
declare module 'brfs/test/path_join.js' {
  declare module.exports: $Exports<'brfs/test/path_join'>;
}
declare module 'brfs/test/readdir.js' {
  declare module.exports: $Exports<'brfs/test/readdir'>;
}
declare module 'brfs/test/require_resolve.js' {
  declare module.exports: $Exports<'brfs/test/require_resolve'>;
}
declare module 'brfs/test/require_resolve/main.js' {
  declare module.exports: $Exports<'brfs/test/require_resolve/main'>;
}
declare module 'brfs/test/separators.js' {
  declare module.exports: $Exports<'brfs/test/separators'>;
}
declare module 'brfs/test/tr.js' {
  declare module.exports: $Exports<'brfs/test/tr'>;
}
declare module 'brfs/test/with_comments.js' {
  declare module.exports: $Exports<'brfs/test/with_comments'>;
}
