// flow-typed signature: 2918e089163b1705bd00fce996724411
// flow-typed version: <<STUB>>/dom-lib_v^1.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-lib/lib/animation/cancelAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/animation/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/animation/nativeRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/animation/requestAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/BrowserSupportCore' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/classNames/addClass' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/classNames/hasClass' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/classNames/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/classNames/removeClass' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/classNames/toggleClass' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/DOMMouseMoveTracker' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/events/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/events/off' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/events/on' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/getVendorPrefixedName' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/normalizeWheel' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/activeElement' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/canUseDOM' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/contains' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getContainer' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getHeight' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getOffset' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getOffsetParent' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getPosition' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getScrollbarSize' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getWidth' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/getWindow' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/isOverflowing' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/nodeName' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/ownerDocument' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/ownerWindow' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/scrollLeft' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/query/scrollTop' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/addStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/camelizeStyleName' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/getComputedStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/getStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/style/removeStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/transition/index' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/transition/translateDOMPositionXY' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/camelize' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/debounce' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/emptyFunction' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/isEventSupported' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/stringFormatter' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/throttle' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/utils/UserAgent_DEPRECATED' {
  declare module.exports: any;
}

declare module 'dom-lib/lib/WheelHandler' {
  declare module.exports: any;
}

declare module 'dom-lib/src/animation/cancelAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'dom-lib/src/animation/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/animation/nativeRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'dom-lib/src/animation/requestAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'dom-lib/src/BrowserSupportCore' {
  declare module.exports: any;
}

declare module 'dom-lib/src/classNames/addClass' {
  declare module.exports: any;
}

declare module 'dom-lib/src/classNames/hasClass' {
  declare module.exports: any;
}

declare module 'dom-lib/src/classNames/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/classNames/removeClass' {
  declare module.exports: any;
}

declare module 'dom-lib/src/classNames/toggleClass' {
  declare module.exports: any;
}

declare module 'dom-lib/src/DOMMouseMoveTracker' {
  declare module.exports: any;
}

declare module 'dom-lib/src/events/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/events/off' {
  declare module.exports: any;
}

declare module 'dom-lib/src/events/on' {
  declare module.exports: any;
}

declare module 'dom-lib/src/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'dom-lib/src/getVendorPrefixedName' {
  declare module.exports: any;
}

declare module 'dom-lib/src/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/normalizeWheel' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/activeElement' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/canUseDOM' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/contains' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getContainer' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getHeight' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getOffset' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getOffsetParent' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getPosition' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getScrollbarSize' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getWidth' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/getWindow' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/isOverflowing' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/nodeName' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/ownerDocument' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/ownerWindow' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/scrollLeft' {
  declare module.exports: any;
}

declare module 'dom-lib/src/query/scrollTop' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/addStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/camelizeStyleName' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/getComputedStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/getStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/style/removeStyle' {
  declare module.exports: any;
}

declare module 'dom-lib/src/transition/index' {
  declare module.exports: any;
}

declare module 'dom-lib/src/transition/translateDOMPositionXY' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/camelize' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/debounce' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/emptyFunction' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/isEventSupported' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/stringFormatter' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/throttle' {
  declare module.exports: any;
}

declare module 'dom-lib/src/utils/UserAgent_DEPRECATED' {
  declare module.exports: any;
}

declare module 'dom-lib/src/WheelHandler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-lib/lib/animation/cancelAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'dom-lib/lib/animation/cancelAnimationFramePolyfill'>;
}
declare module 'dom-lib/lib/animation/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/animation/index'>;
}
declare module 'dom-lib/lib/animation/nativeRequestAnimationFrame.js' {
  declare module.exports: $Exports<'dom-lib/lib/animation/nativeRequestAnimationFrame'>;
}
declare module 'dom-lib/lib/animation/requestAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'dom-lib/lib/animation/requestAnimationFramePolyfill'>;
}
declare module 'dom-lib/lib/BrowserSupportCore.js' {
  declare module.exports: $Exports<'dom-lib/lib/BrowserSupportCore'>;
}
declare module 'dom-lib/lib/classNames/addClass.js' {
  declare module.exports: $Exports<'dom-lib/lib/classNames/addClass'>;
}
declare module 'dom-lib/lib/classNames/hasClass.js' {
  declare module.exports: $Exports<'dom-lib/lib/classNames/hasClass'>;
}
declare module 'dom-lib/lib/classNames/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/classNames/index'>;
}
declare module 'dom-lib/lib/classNames/removeClass.js' {
  declare module.exports: $Exports<'dom-lib/lib/classNames/removeClass'>;
}
declare module 'dom-lib/lib/classNames/toggleClass.js' {
  declare module.exports: $Exports<'dom-lib/lib/classNames/toggleClass'>;
}
declare module 'dom-lib/lib/DOMMouseMoveTracker.js' {
  declare module.exports: $Exports<'dom-lib/lib/DOMMouseMoveTracker'>;
}
declare module 'dom-lib/lib/events/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/events/index'>;
}
declare module 'dom-lib/lib/events/off.js' {
  declare module.exports: $Exports<'dom-lib/lib/events/off'>;
}
declare module 'dom-lib/lib/events/on.js' {
  declare module.exports: $Exports<'dom-lib/lib/events/on'>;
}
declare module 'dom-lib/lib/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'dom-lib/lib/ExecutionEnvironment'>;
}
declare module 'dom-lib/lib/getVendorPrefixedName.js' {
  declare module.exports: $Exports<'dom-lib/lib/getVendorPrefixedName'>;
}
declare module 'dom-lib/lib/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/index'>;
}
declare module 'dom-lib/lib/normalizeWheel.js' {
  declare module.exports: $Exports<'dom-lib/lib/normalizeWheel'>;
}
declare module 'dom-lib/lib/query/activeElement.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/activeElement'>;
}
declare module 'dom-lib/lib/query/canUseDOM.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/canUseDOM'>;
}
declare module 'dom-lib/lib/query/contains.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/contains'>;
}
declare module 'dom-lib/lib/query/getContainer.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getContainer'>;
}
declare module 'dom-lib/lib/query/getHeight.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getHeight'>;
}
declare module 'dom-lib/lib/query/getOffset.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getOffset'>;
}
declare module 'dom-lib/lib/query/getOffsetParent.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getOffsetParent'>;
}
declare module 'dom-lib/lib/query/getPosition.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getPosition'>;
}
declare module 'dom-lib/lib/query/getScrollbarSize.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getScrollbarSize'>;
}
declare module 'dom-lib/lib/query/getWidth.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getWidth'>;
}
declare module 'dom-lib/lib/query/getWindow.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/getWindow'>;
}
declare module 'dom-lib/lib/query/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/index'>;
}
declare module 'dom-lib/lib/query/isOverflowing.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/isOverflowing'>;
}
declare module 'dom-lib/lib/query/nodeName.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/nodeName'>;
}
declare module 'dom-lib/lib/query/ownerDocument.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/ownerDocument'>;
}
declare module 'dom-lib/lib/query/ownerWindow.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/ownerWindow'>;
}
declare module 'dom-lib/lib/query/scrollLeft.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/scrollLeft'>;
}
declare module 'dom-lib/lib/query/scrollTop.js' {
  declare module.exports: $Exports<'dom-lib/lib/query/scrollTop'>;
}
declare module 'dom-lib/lib/style/addStyle.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/addStyle'>;
}
declare module 'dom-lib/lib/style/camelizeStyleName.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/camelizeStyleName'>;
}
declare module 'dom-lib/lib/style/getComputedStyle.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/getComputedStyle'>;
}
declare module 'dom-lib/lib/style/getStyle.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/getStyle'>;
}
declare module 'dom-lib/lib/style/hyphenateStyleName.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/hyphenateStyleName'>;
}
declare module 'dom-lib/lib/style/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/index'>;
}
declare module 'dom-lib/lib/style/removeStyle.js' {
  declare module.exports: $Exports<'dom-lib/lib/style/removeStyle'>;
}
declare module 'dom-lib/lib/transition/index.js' {
  declare module.exports: $Exports<'dom-lib/lib/transition/index'>;
}
declare module 'dom-lib/lib/transition/translateDOMPositionXY.js' {
  declare module.exports: $Exports<'dom-lib/lib/transition/translateDOMPositionXY'>;
}
declare module 'dom-lib/lib/utils/camelize.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/camelize'>;
}
declare module 'dom-lib/lib/utils/debounce.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/debounce'>;
}
declare module 'dom-lib/lib/utils/emptyFunction.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/emptyFunction'>;
}
declare module 'dom-lib/lib/utils/isEventSupported.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/isEventSupported'>;
}
declare module 'dom-lib/lib/utils/stringFormatter.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/stringFormatter'>;
}
declare module 'dom-lib/lib/utils/throttle.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/throttle'>;
}
declare module 'dom-lib/lib/utils/UserAgent_DEPRECATED.js' {
  declare module.exports: $Exports<'dom-lib/lib/utils/UserAgent_DEPRECATED'>;
}
declare module 'dom-lib/lib/WheelHandler.js' {
  declare module.exports: $Exports<'dom-lib/lib/WheelHandler'>;
}
declare module 'dom-lib/src/animation/cancelAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'dom-lib/src/animation/cancelAnimationFramePolyfill'>;
}
declare module 'dom-lib/src/animation/index.js' {
  declare module.exports: $Exports<'dom-lib/src/animation/index'>;
}
declare module 'dom-lib/src/animation/nativeRequestAnimationFrame.js' {
  declare module.exports: $Exports<'dom-lib/src/animation/nativeRequestAnimationFrame'>;
}
declare module 'dom-lib/src/animation/requestAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'dom-lib/src/animation/requestAnimationFramePolyfill'>;
}
declare module 'dom-lib/src/BrowserSupportCore.js' {
  declare module.exports: $Exports<'dom-lib/src/BrowserSupportCore'>;
}
declare module 'dom-lib/src/classNames/addClass.js' {
  declare module.exports: $Exports<'dom-lib/src/classNames/addClass'>;
}
declare module 'dom-lib/src/classNames/hasClass.js' {
  declare module.exports: $Exports<'dom-lib/src/classNames/hasClass'>;
}
declare module 'dom-lib/src/classNames/index.js' {
  declare module.exports: $Exports<'dom-lib/src/classNames/index'>;
}
declare module 'dom-lib/src/classNames/removeClass.js' {
  declare module.exports: $Exports<'dom-lib/src/classNames/removeClass'>;
}
declare module 'dom-lib/src/classNames/toggleClass.js' {
  declare module.exports: $Exports<'dom-lib/src/classNames/toggleClass'>;
}
declare module 'dom-lib/src/DOMMouseMoveTracker.js' {
  declare module.exports: $Exports<'dom-lib/src/DOMMouseMoveTracker'>;
}
declare module 'dom-lib/src/events/index.js' {
  declare module.exports: $Exports<'dom-lib/src/events/index'>;
}
declare module 'dom-lib/src/events/off.js' {
  declare module.exports: $Exports<'dom-lib/src/events/off'>;
}
declare module 'dom-lib/src/events/on.js' {
  declare module.exports: $Exports<'dom-lib/src/events/on'>;
}
declare module 'dom-lib/src/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'dom-lib/src/ExecutionEnvironment'>;
}
declare module 'dom-lib/src/getVendorPrefixedName.js' {
  declare module.exports: $Exports<'dom-lib/src/getVendorPrefixedName'>;
}
declare module 'dom-lib/src/index.js' {
  declare module.exports: $Exports<'dom-lib/src/index'>;
}
declare module 'dom-lib/src/normalizeWheel.js' {
  declare module.exports: $Exports<'dom-lib/src/normalizeWheel'>;
}
declare module 'dom-lib/src/query/activeElement.js' {
  declare module.exports: $Exports<'dom-lib/src/query/activeElement'>;
}
declare module 'dom-lib/src/query/canUseDOM.js' {
  declare module.exports: $Exports<'dom-lib/src/query/canUseDOM'>;
}
declare module 'dom-lib/src/query/contains.js' {
  declare module.exports: $Exports<'dom-lib/src/query/contains'>;
}
declare module 'dom-lib/src/query/getContainer.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getContainer'>;
}
declare module 'dom-lib/src/query/getHeight.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getHeight'>;
}
declare module 'dom-lib/src/query/getOffset.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getOffset'>;
}
declare module 'dom-lib/src/query/getOffsetParent.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getOffsetParent'>;
}
declare module 'dom-lib/src/query/getPosition.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getPosition'>;
}
declare module 'dom-lib/src/query/getScrollbarSize.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getScrollbarSize'>;
}
declare module 'dom-lib/src/query/getWidth.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getWidth'>;
}
declare module 'dom-lib/src/query/getWindow.js' {
  declare module.exports: $Exports<'dom-lib/src/query/getWindow'>;
}
declare module 'dom-lib/src/query/index.js' {
  declare module.exports: $Exports<'dom-lib/src/query/index'>;
}
declare module 'dom-lib/src/query/isOverflowing.js' {
  declare module.exports: $Exports<'dom-lib/src/query/isOverflowing'>;
}
declare module 'dom-lib/src/query/nodeName.js' {
  declare module.exports: $Exports<'dom-lib/src/query/nodeName'>;
}
declare module 'dom-lib/src/query/ownerDocument.js' {
  declare module.exports: $Exports<'dom-lib/src/query/ownerDocument'>;
}
declare module 'dom-lib/src/query/ownerWindow.js' {
  declare module.exports: $Exports<'dom-lib/src/query/ownerWindow'>;
}
declare module 'dom-lib/src/query/scrollLeft.js' {
  declare module.exports: $Exports<'dom-lib/src/query/scrollLeft'>;
}
declare module 'dom-lib/src/query/scrollTop.js' {
  declare module.exports: $Exports<'dom-lib/src/query/scrollTop'>;
}
declare module 'dom-lib/src/style/addStyle.js' {
  declare module.exports: $Exports<'dom-lib/src/style/addStyle'>;
}
declare module 'dom-lib/src/style/camelizeStyleName.js' {
  declare module.exports: $Exports<'dom-lib/src/style/camelizeStyleName'>;
}
declare module 'dom-lib/src/style/getComputedStyle.js' {
  declare module.exports: $Exports<'dom-lib/src/style/getComputedStyle'>;
}
declare module 'dom-lib/src/style/getStyle.js' {
  declare module.exports: $Exports<'dom-lib/src/style/getStyle'>;
}
declare module 'dom-lib/src/style/hyphenateStyleName.js' {
  declare module.exports: $Exports<'dom-lib/src/style/hyphenateStyleName'>;
}
declare module 'dom-lib/src/style/index.js' {
  declare module.exports: $Exports<'dom-lib/src/style/index'>;
}
declare module 'dom-lib/src/style/removeStyle.js' {
  declare module.exports: $Exports<'dom-lib/src/style/removeStyle'>;
}
declare module 'dom-lib/src/transition/index.js' {
  declare module.exports: $Exports<'dom-lib/src/transition/index'>;
}
declare module 'dom-lib/src/transition/translateDOMPositionXY.js' {
  declare module.exports: $Exports<'dom-lib/src/transition/translateDOMPositionXY'>;
}
declare module 'dom-lib/src/utils/camelize.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/camelize'>;
}
declare module 'dom-lib/src/utils/debounce.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/debounce'>;
}
declare module 'dom-lib/src/utils/emptyFunction.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/emptyFunction'>;
}
declare module 'dom-lib/src/utils/isEventSupported.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/isEventSupported'>;
}
declare module 'dom-lib/src/utils/stringFormatter.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/stringFormatter'>;
}
declare module 'dom-lib/src/utils/throttle.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/throttle'>;
}
declare module 'dom-lib/src/utils/UserAgent_DEPRECATED.js' {
  declare module.exports: $Exports<'dom-lib/src/utils/UserAgent_DEPRECATED'>;
}
declare module 'dom-lib/src/WheelHandler.js' {
  declare module.exports: $Exports<'dom-lib/src/WheelHandler'>;
}
