// flow-typed signature: dafa94aaecf7fc2736895ab3c7fa5f88
// flow-typed version: <<STUB>>/gulp-postcss_v^7.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-postcss/index' {
  declare module.exports: $Exports<'gulp-postcss'>;
}
declare module 'gulp-postcss/index.js' {
  declare module.exports: $Exports<'gulp-postcss'>;
}
