// flow-typed signature: 8611cba5ed6a063d5f4c5ce23d44439d
// flow-typed version: <<STUB>>/gulp-postcss_v^7.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-postcss/index' {
  declare module.exports: $Exports<'gulp-postcss'>;
}
declare module 'gulp-postcss/index.js' {
  declare module.exports: $Exports<'gulp-postcss'>;
}
