// flow-typed signature: c6d9d7c242f354f1f1915ee4ca8ce8ab
// flow-typed version: <<STUB>>/gulp-less_v^4.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-less/index' {
  declare module.exports: $Exports<'gulp-less'>;
}
declare module 'gulp-less/index.js' {
  declare module.exports: $Exports<'gulp-less'>;
}
