// flow-typed signature: a0fbabc6c33596f828b90a81e6288896
// flow-typed version: <<STUB>>/gulp-sourcemaps_v^2.6.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-sourcemaps/src/debug' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/init/index.internals' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/init/index' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/utils' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/write/index.internals' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/write/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-sourcemaps/index' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
declare module 'gulp-sourcemaps/index.js' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
declare module 'gulp-sourcemaps/src/debug.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/debug'>;
}
declare module 'gulp-sourcemaps/src/init/index.internals.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/init/index.internals'>;
}
declare module 'gulp-sourcemaps/src/init/index.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/init/index'>;
}
declare module 'gulp-sourcemaps/src/utils.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/utils'>;
}
declare module 'gulp-sourcemaps/src/write/index.internals.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/write/index.internals'>;
}
declare module 'gulp-sourcemaps/src/write/index.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/write/index'>;
}
