// flow-typed signature: fc798038d94f3ffa7ce84516cb1ad768
// flow-typed version: <<STUB>>/moment_v^2.22.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment/ender' {
  declare module.exports: any;
}

declare module 'moment/locale/af' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-dz' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-kw' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-ly' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-ma' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-sa' {
  declare module.exports: any;
}

declare module 'moment/locale/ar-tn' {
  declare module.exports: any;
}

declare module 'moment/locale/ar' {
  declare module.exports: any;
}

declare module 'moment/locale/az' {
  declare module.exports: any;
}

declare module 'moment/locale/be' {
  declare module.exports: any;
}

declare module 'moment/locale/bg' {
  declare module.exports: any;
}

declare module 'moment/locale/bm' {
  declare module.exports: any;
}

declare module 'moment/locale/bn' {
  declare module.exports: any;
}

declare module 'moment/locale/bo' {
  declare module.exports: any;
}

declare module 'moment/locale/br' {
  declare module.exports: any;
}

declare module 'moment/locale/bs' {
  declare module.exports: any;
}

declare module 'moment/locale/ca' {
  declare module.exports: any;
}

declare module 'moment/locale/cs' {
  declare module.exports: any;
}

declare module 'moment/locale/cv' {
  declare module.exports: any;
}

declare module 'moment/locale/cy' {
  declare module.exports: any;
}

declare module 'moment/locale/da' {
  declare module.exports: any;
}

declare module 'moment/locale/de-at' {
  declare module.exports: any;
}

declare module 'moment/locale/de-ch' {
  declare module.exports: any;
}

declare module 'moment/locale/de' {
  declare module.exports: any;
}

declare module 'moment/locale/dv' {
  declare module.exports: any;
}

declare module 'moment/locale/el' {
  declare module.exports: any;
}

declare module 'moment/locale/en-au' {
  declare module.exports: any;
}

declare module 'moment/locale/en-ca' {
  declare module.exports: any;
}

declare module 'moment/locale/en-gb' {
  declare module.exports: any;
}

declare module 'moment/locale/en-ie' {
  declare module.exports: any;
}

declare module 'moment/locale/en-il' {
  declare module.exports: any;
}

declare module 'moment/locale/en-nz' {
  declare module.exports: any;
}

declare module 'moment/locale/eo' {
  declare module.exports: any;
}

declare module 'moment/locale/es-do' {
  declare module.exports: any;
}

declare module 'moment/locale/es-us' {
  declare module.exports: any;
}

declare module 'moment/locale/es' {
  declare module.exports: any;
}

declare module 'moment/locale/et' {
  declare module.exports: any;
}

declare module 'moment/locale/eu' {
  declare module.exports: any;
}

declare module 'moment/locale/fa' {
  declare module.exports: any;
}

declare module 'moment/locale/fi' {
  declare module.exports: any;
}

declare module 'moment/locale/fo' {
  declare module.exports: any;
}

declare module 'moment/locale/fr-ca' {
  declare module.exports: any;
}

declare module 'moment/locale/fr-ch' {
  declare module.exports: any;
}

declare module 'moment/locale/fr' {
  declare module.exports: any;
}

declare module 'moment/locale/fy' {
  declare module.exports: any;
}

declare module 'moment/locale/gd' {
  declare module.exports: any;
}

declare module 'moment/locale/gl' {
  declare module.exports: any;
}

declare module 'moment/locale/gom-latn' {
  declare module.exports: any;
}

declare module 'moment/locale/gu' {
  declare module.exports: any;
}

declare module 'moment/locale/he' {
  declare module.exports: any;
}

declare module 'moment/locale/hi' {
  declare module.exports: any;
}

declare module 'moment/locale/hr' {
  declare module.exports: any;
}

declare module 'moment/locale/hu' {
  declare module.exports: any;
}

declare module 'moment/locale/hy-am' {
  declare module.exports: any;
}

declare module 'moment/locale/id' {
  declare module.exports: any;
}

declare module 'moment/locale/is' {
  declare module.exports: any;
}

declare module 'moment/locale/it' {
  declare module.exports: any;
}

declare module 'moment/locale/ja' {
  declare module.exports: any;
}

declare module 'moment/locale/jv' {
  declare module.exports: any;
}

declare module 'moment/locale/ka' {
  declare module.exports: any;
}

declare module 'moment/locale/kk' {
  declare module.exports: any;
}

declare module 'moment/locale/km' {
  declare module.exports: any;
}

declare module 'moment/locale/kn' {
  declare module.exports: any;
}

declare module 'moment/locale/ko' {
  declare module.exports: any;
}

declare module 'moment/locale/ky' {
  declare module.exports: any;
}

declare module 'moment/locale/lb' {
  declare module.exports: any;
}

declare module 'moment/locale/lo' {
  declare module.exports: any;
}

declare module 'moment/locale/lt' {
  declare module.exports: any;
}

declare module 'moment/locale/lv' {
  declare module.exports: any;
}

declare module 'moment/locale/me' {
  declare module.exports: any;
}

declare module 'moment/locale/mi' {
  declare module.exports: any;
}

declare module 'moment/locale/mk' {
  declare module.exports: any;
}

declare module 'moment/locale/ml' {
  declare module.exports: any;
}

declare module 'moment/locale/mn' {
  declare module.exports: any;
}

declare module 'moment/locale/mr' {
  declare module.exports: any;
}

declare module 'moment/locale/ms-my' {
  declare module.exports: any;
}

declare module 'moment/locale/ms' {
  declare module.exports: any;
}

declare module 'moment/locale/mt' {
  declare module.exports: any;
}

declare module 'moment/locale/my' {
  declare module.exports: any;
}

declare module 'moment/locale/nb' {
  declare module.exports: any;
}

declare module 'moment/locale/ne' {
  declare module.exports: any;
}

declare module 'moment/locale/nl-be' {
  declare module.exports: any;
}

declare module 'moment/locale/nl' {
  declare module.exports: any;
}

declare module 'moment/locale/nn' {
  declare module.exports: any;
}

declare module 'moment/locale/pa-in' {
  declare module.exports: any;
}

declare module 'moment/locale/pl' {
  declare module.exports: any;
}

declare module 'moment/locale/pt-br' {
  declare module.exports: any;
}

declare module 'moment/locale/pt' {
  declare module.exports: any;
}

declare module 'moment/locale/ro' {
  declare module.exports: any;
}

declare module 'moment/locale/ru' {
  declare module.exports: any;
}

declare module 'moment/locale/sd' {
  declare module.exports: any;
}

declare module 'moment/locale/se' {
  declare module.exports: any;
}

declare module 'moment/locale/si' {
  declare module.exports: any;
}

declare module 'moment/locale/sk' {
  declare module.exports: any;
}

declare module 'moment/locale/sl' {
  declare module.exports: any;
}

declare module 'moment/locale/sq' {
  declare module.exports: any;
}

declare module 'moment/locale/sr-cyrl' {
  declare module.exports: any;
}

declare module 'moment/locale/sr' {
  declare module.exports: any;
}

declare module 'moment/locale/ss' {
  declare module.exports: any;
}

declare module 'moment/locale/sv' {
  declare module.exports: any;
}

declare module 'moment/locale/sw' {
  declare module.exports: any;
}

declare module 'moment/locale/ta' {
  declare module.exports: any;
}

declare module 'moment/locale/te' {
  declare module.exports: any;
}

declare module 'moment/locale/tet' {
  declare module.exports: any;
}

declare module 'moment/locale/tg' {
  declare module.exports: any;
}

declare module 'moment/locale/th' {
  declare module.exports: any;
}

declare module 'moment/locale/tl-ph' {
  declare module.exports: any;
}

declare module 'moment/locale/tlh' {
  declare module.exports: any;
}

declare module 'moment/locale/tr' {
  declare module.exports: any;
}

declare module 'moment/locale/tzl' {
  declare module.exports: any;
}

declare module 'moment/locale/tzm-latn' {
  declare module.exports: any;
}

declare module 'moment/locale/tzm' {
  declare module.exports: any;
}

declare module 'moment/locale/ug-cn' {
  declare module.exports: any;
}

declare module 'moment/locale/uk' {
  declare module.exports: any;
}

declare module 'moment/locale/ur' {
  declare module.exports: any;
}

declare module 'moment/locale/uz-latn' {
  declare module.exports: any;
}

declare module 'moment/locale/uz' {
  declare module.exports: any;
}

declare module 'moment/locale/vi' {
  declare module.exports: any;
}

declare module 'moment/locale/x-pseudo' {
  declare module.exports: any;
}

declare module 'moment/locale/yo' {
  declare module.exports: any;
}

declare module 'moment/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'moment/locale/zh-hk' {
  declare module.exports: any;
}

declare module 'moment/locale/zh-tw' {
  declare module.exports: any;
}

declare module 'moment/min/locales' {
  declare module.exports: any;
}

declare module 'moment/min/locales.min' {
  declare module.exports: any;
}

declare module 'moment/min/moment-with-locales' {
  declare module.exports: any;
}

declare module 'moment/min/moment-with-locales.min' {
  declare module.exports: any;
}

declare module 'moment/min/moment.min' {
  declare module.exports: any;
}

declare module 'moment/moment' {
  declare module.exports: any;
}

declare module 'moment/package' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/check-overflow' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/date-from-array' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-anything' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-array' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-object' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-string-and-array' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-string-and-format' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/from-string' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/local' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/parsing-flags' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/utc' {
  declare module.exports: any;
}

declare module 'moment/src/lib/create/valid' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/abs' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/add-subtract' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/as' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/bubble' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/clone' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/constructor' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/create' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/duration' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/get' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/humanize' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/iso-string' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/prototype' {
  declare module.exports: any;
}

declare module 'moment/src/lib/duration/valid' {
  declare module.exports: any;
}

declare module 'moment/src/lib/format/format' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/base-config' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/calendar' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/constructor' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/en' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/formats' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/invalid' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/lists' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/locale' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/locales' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/ordinal' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/pre-post-format' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/prototype' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/relative' {
  declare module.exports: any;
}

declare module 'moment/src/lib/locale/set' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/add-subtract' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/calendar' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/clone' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/compare' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/constructor' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/creation-data' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/diff' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/format' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/from' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/get-set' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/locale' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/min-max' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/moment' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/now' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/prototype' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/start-end-of' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/to-type' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/to' {
  declare module.exports: any;
}

declare module 'moment/src/lib/moment/valid' {
  declare module.exports: any;
}

declare module 'moment/src/lib/parse/regex' {
  declare module.exports: any;
}

declare module 'moment/src/lib/parse/token' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/aliases' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/constants' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/day-of-month' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/day-of-week' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/day-of-year' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/hour' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/millisecond' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/minute' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/month' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/offset' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/priorities' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/quarter' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/second' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/timestamp' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/timezone' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/units' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/week-calendar-utils' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/week-year' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/week' {
  declare module.exports: any;
}

declare module 'moment/src/lib/units/year' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/abs-ceil' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/abs-floor' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/abs-round' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/compare-arrays' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/defaults' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/deprecate' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/extend' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/has-own-prop' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/hooks' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/index-of' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-array' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-date' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-function' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-number' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-object-empty' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-object' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/is-undefined' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/keys' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/map' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/mod' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/some' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/to-int' {
  declare module.exports: any;
}

declare module 'moment/src/lib/utils/zero-fill' {
  declare module.exports: any;
}

declare module 'moment/src/locale/af' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-dz' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-kw' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-ly' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-ma' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-sa' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar-tn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ar' {
  declare module.exports: any;
}

declare module 'moment/src/locale/az' {
  declare module.exports: any;
}

declare module 'moment/src/locale/be' {
  declare module.exports: any;
}

declare module 'moment/src/locale/bg' {
  declare module.exports: any;
}

declare module 'moment/src/locale/bm' {
  declare module.exports: any;
}

declare module 'moment/src/locale/bn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/bo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/br' {
  declare module.exports: any;
}

declare module 'moment/src/locale/bs' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ca' {
  declare module.exports: any;
}

declare module 'moment/src/locale/cs' {
  declare module.exports: any;
}

declare module 'moment/src/locale/cv' {
  declare module.exports: any;
}

declare module 'moment/src/locale/cy' {
  declare module.exports: any;
}

declare module 'moment/src/locale/da' {
  declare module.exports: any;
}

declare module 'moment/src/locale/de-at' {
  declare module.exports: any;
}

declare module 'moment/src/locale/de-ch' {
  declare module.exports: any;
}

declare module 'moment/src/locale/de' {
  declare module.exports: any;
}

declare module 'moment/src/locale/dv' {
  declare module.exports: any;
}

declare module 'moment/src/locale/el' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-au' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-ca' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-gb' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-ie' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-il' {
  declare module.exports: any;
}

declare module 'moment/src/locale/en-nz' {
  declare module.exports: any;
}

declare module 'moment/src/locale/eo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/es-do' {
  declare module.exports: any;
}

declare module 'moment/src/locale/es-us' {
  declare module.exports: any;
}

declare module 'moment/src/locale/es' {
  declare module.exports: any;
}

declare module 'moment/src/locale/et' {
  declare module.exports: any;
}

declare module 'moment/src/locale/eu' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fa' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fi' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fr-ca' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fr-ch' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fr' {
  declare module.exports: any;
}

declare module 'moment/src/locale/fy' {
  declare module.exports: any;
}

declare module 'moment/src/locale/gd' {
  declare module.exports: any;
}

declare module 'moment/src/locale/gl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/gom-latn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/gu' {
  declare module.exports: any;
}

declare module 'moment/src/locale/he' {
  declare module.exports: any;
}

declare module 'moment/src/locale/hi' {
  declare module.exports: any;
}

declare module 'moment/src/locale/hr' {
  declare module.exports: any;
}

declare module 'moment/src/locale/hu' {
  declare module.exports: any;
}

declare module 'moment/src/locale/hy-am' {
  declare module.exports: any;
}

declare module 'moment/src/locale/id' {
  declare module.exports: any;
}

declare module 'moment/src/locale/is' {
  declare module.exports: any;
}

declare module 'moment/src/locale/it' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ja' {
  declare module.exports: any;
}

declare module 'moment/src/locale/jv' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ka' {
  declare module.exports: any;
}

declare module 'moment/src/locale/kk' {
  declare module.exports: any;
}

declare module 'moment/src/locale/km' {
  declare module.exports: any;
}

declare module 'moment/src/locale/kn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ko' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ky' {
  declare module.exports: any;
}

declare module 'moment/src/locale/lb' {
  declare module.exports: any;
}

declare module 'moment/src/locale/lo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/lt' {
  declare module.exports: any;
}

declare module 'moment/src/locale/lv' {
  declare module.exports: any;
}

declare module 'moment/src/locale/me' {
  declare module.exports: any;
}

declare module 'moment/src/locale/mi' {
  declare module.exports: any;
}

declare module 'moment/src/locale/mk' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ml' {
  declare module.exports: any;
}

declare module 'moment/src/locale/mn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/mr' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ms-my' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ms' {
  declare module.exports: any;
}

declare module 'moment/src/locale/mt' {
  declare module.exports: any;
}

declare module 'moment/src/locale/my' {
  declare module.exports: any;
}

declare module 'moment/src/locale/nb' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ne' {
  declare module.exports: any;
}

declare module 'moment/src/locale/nl-be' {
  declare module.exports: any;
}

declare module 'moment/src/locale/nl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/nn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/pa-in' {
  declare module.exports: any;
}

declare module 'moment/src/locale/pl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/pt-br' {
  declare module.exports: any;
}

declare module 'moment/src/locale/pt' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ro' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ru' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sd' {
  declare module.exports: any;
}

declare module 'moment/src/locale/se' {
  declare module.exports: any;
}

declare module 'moment/src/locale/si' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sk' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sq' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sr-cyrl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sr' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ss' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sv' {
  declare module.exports: any;
}

declare module 'moment/src/locale/sw' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ta' {
  declare module.exports: any;
}

declare module 'moment/src/locale/te' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tet' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tg' {
  declare module.exports: any;
}

declare module 'moment/src/locale/th' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tl-ph' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tlh' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tr' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tzl' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tzm-latn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/tzm' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ug-cn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/uk' {
  declare module.exports: any;
}

declare module 'moment/src/locale/ur' {
  declare module.exports: any;
}

declare module 'moment/src/locale/uz-latn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/uz' {
  declare module.exports: any;
}

declare module 'moment/src/locale/vi' {
  declare module.exports: any;
}

declare module 'moment/src/locale/x-pseudo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/yo' {
  declare module.exports: any;
}

declare module 'moment/src/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'moment/src/locale/zh-hk' {
  declare module.exports: any;
}

declare module 'moment/src/locale/zh-tw' {
  declare module.exports: any;
}

declare module 'moment/src/moment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment/ender.js' {
  declare module.exports: $Exports<'moment/ender'>;
}
declare module 'moment/locale/af.js' {
  declare module.exports: $Exports<'moment/locale/af'>;
}
declare module 'moment/locale/ar-dz.js' {
  declare module.exports: $Exports<'moment/locale/ar-dz'>;
}
declare module 'moment/locale/ar-kw.js' {
  declare module.exports: $Exports<'moment/locale/ar-kw'>;
}
declare module 'moment/locale/ar-ly.js' {
  declare module.exports: $Exports<'moment/locale/ar-ly'>;
}
declare module 'moment/locale/ar-ma.js' {
  declare module.exports: $Exports<'moment/locale/ar-ma'>;
}
declare module 'moment/locale/ar-sa.js' {
  declare module.exports: $Exports<'moment/locale/ar-sa'>;
}
declare module 'moment/locale/ar-tn.js' {
  declare module.exports: $Exports<'moment/locale/ar-tn'>;
}
declare module 'moment/locale/ar.js' {
  declare module.exports: $Exports<'moment/locale/ar'>;
}
declare module 'moment/locale/az.js' {
  declare module.exports: $Exports<'moment/locale/az'>;
}
declare module 'moment/locale/be.js' {
  declare module.exports: $Exports<'moment/locale/be'>;
}
declare module 'moment/locale/bg.js' {
  declare module.exports: $Exports<'moment/locale/bg'>;
}
declare module 'moment/locale/bm.js' {
  declare module.exports: $Exports<'moment/locale/bm'>;
}
declare module 'moment/locale/bn.js' {
  declare module.exports: $Exports<'moment/locale/bn'>;
}
declare module 'moment/locale/bo.js' {
  declare module.exports: $Exports<'moment/locale/bo'>;
}
declare module 'moment/locale/br.js' {
  declare module.exports: $Exports<'moment/locale/br'>;
}
declare module 'moment/locale/bs.js' {
  declare module.exports: $Exports<'moment/locale/bs'>;
}
declare module 'moment/locale/ca.js' {
  declare module.exports: $Exports<'moment/locale/ca'>;
}
declare module 'moment/locale/cs.js' {
  declare module.exports: $Exports<'moment/locale/cs'>;
}
declare module 'moment/locale/cv.js' {
  declare module.exports: $Exports<'moment/locale/cv'>;
}
declare module 'moment/locale/cy.js' {
  declare module.exports: $Exports<'moment/locale/cy'>;
}
declare module 'moment/locale/da.js' {
  declare module.exports: $Exports<'moment/locale/da'>;
}
declare module 'moment/locale/de-at.js' {
  declare module.exports: $Exports<'moment/locale/de-at'>;
}
declare module 'moment/locale/de-ch.js' {
  declare module.exports: $Exports<'moment/locale/de-ch'>;
}
declare module 'moment/locale/de.js' {
  declare module.exports: $Exports<'moment/locale/de'>;
}
declare module 'moment/locale/dv.js' {
  declare module.exports: $Exports<'moment/locale/dv'>;
}
declare module 'moment/locale/el.js' {
  declare module.exports: $Exports<'moment/locale/el'>;
}
declare module 'moment/locale/en-au.js' {
  declare module.exports: $Exports<'moment/locale/en-au'>;
}
declare module 'moment/locale/en-ca.js' {
  declare module.exports: $Exports<'moment/locale/en-ca'>;
}
declare module 'moment/locale/en-gb.js' {
  declare module.exports: $Exports<'moment/locale/en-gb'>;
}
declare module 'moment/locale/en-ie.js' {
  declare module.exports: $Exports<'moment/locale/en-ie'>;
}
declare module 'moment/locale/en-il.js' {
  declare module.exports: $Exports<'moment/locale/en-il'>;
}
declare module 'moment/locale/en-nz.js' {
  declare module.exports: $Exports<'moment/locale/en-nz'>;
}
declare module 'moment/locale/eo.js' {
  declare module.exports: $Exports<'moment/locale/eo'>;
}
declare module 'moment/locale/es-do.js' {
  declare module.exports: $Exports<'moment/locale/es-do'>;
}
declare module 'moment/locale/es-us.js' {
  declare module.exports: $Exports<'moment/locale/es-us'>;
}
declare module 'moment/locale/es.js' {
  declare module.exports: $Exports<'moment/locale/es'>;
}
declare module 'moment/locale/et.js' {
  declare module.exports: $Exports<'moment/locale/et'>;
}
declare module 'moment/locale/eu.js' {
  declare module.exports: $Exports<'moment/locale/eu'>;
}
declare module 'moment/locale/fa.js' {
  declare module.exports: $Exports<'moment/locale/fa'>;
}
declare module 'moment/locale/fi.js' {
  declare module.exports: $Exports<'moment/locale/fi'>;
}
declare module 'moment/locale/fo.js' {
  declare module.exports: $Exports<'moment/locale/fo'>;
}
declare module 'moment/locale/fr-ca.js' {
  declare module.exports: $Exports<'moment/locale/fr-ca'>;
}
declare module 'moment/locale/fr-ch.js' {
  declare module.exports: $Exports<'moment/locale/fr-ch'>;
}
declare module 'moment/locale/fr.js' {
  declare module.exports: $Exports<'moment/locale/fr'>;
}
declare module 'moment/locale/fy.js' {
  declare module.exports: $Exports<'moment/locale/fy'>;
}
declare module 'moment/locale/gd.js' {
  declare module.exports: $Exports<'moment/locale/gd'>;
}
declare module 'moment/locale/gl.js' {
  declare module.exports: $Exports<'moment/locale/gl'>;
}
declare module 'moment/locale/gom-latn.js' {
  declare module.exports: $Exports<'moment/locale/gom-latn'>;
}
declare module 'moment/locale/gu.js' {
  declare module.exports: $Exports<'moment/locale/gu'>;
}
declare module 'moment/locale/he.js' {
  declare module.exports: $Exports<'moment/locale/he'>;
}
declare module 'moment/locale/hi.js' {
  declare module.exports: $Exports<'moment/locale/hi'>;
}
declare module 'moment/locale/hr.js' {
  declare module.exports: $Exports<'moment/locale/hr'>;
}
declare module 'moment/locale/hu.js' {
  declare module.exports: $Exports<'moment/locale/hu'>;
}
declare module 'moment/locale/hy-am.js' {
  declare module.exports: $Exports<'moment/locale/hy-am'>;
}
declare module 'moment/locale/id.js' {
  declare module.exports: $Exports<'moment/locale/id'>;
}
declare module 'moment/locale/is.js' {
  declare module.exports: $Exports<'moment/locale/is'>;
}
declare module 'moment/locale/it.js' {
  declare module.exports: $Exports<'moment/locale/it'>;
}
declare module 'moment/locale/ja.js' {
  declare module.exports: $Exports<'moment/locale/ja'>;
}
declare module 'moment/locale/jv.js' {
  declare module.exports: $Exports<'moment/locale/jv'>;
}
declare module 'moment/locale/ka.js' {
  declare module.exports: $Exports<'moment/locale/ka'>;
}
declare module 'moment/locale/kk.js' {
  declare module.exports: $Exports<'moment/locale/kk'>;
}
declare module 'moment/locale/km.js' {
  declare module.exports: $Exports<'moment/locale/km'>;
}
declare module 'moment/locale/kn.js' {
  declare module.exports: $Exports<'moment/locale/kn'>;
}
declare module 'moment/locale/ko.js' {
  declare module.exports: $Exports<'moment/locale/ko'>;
}
declare module 'moment/locale/ky.js' {
  declare module.exports: $Exports<'moment/locale/ky'>;
}
declare module 'moment/locale/lb.js' {
  declare module.exports: $Exports<'moment/locale/lb'>;
}
declare module 'moment/locale/lo.js' {
  declare module.exports: $Exports<'moment/locale/lo'>;
}
declare module 'moment/locale/lt.js' {
  declare module.exports: $Exports<'moment/locale/lt'>;
}
declare module 'moment/locale/lv.js' {
  declare module.exports: $Exports<'moment/locale/lv'>;
}
declare module 'moment/locale/me.js' {
  declare module.exports: $Exports<'moment/locale/me'>;
}
declare module 'moment/locale/mi.js' {
  declare module.exports: $Exports<'moment/locale/mi'>;
}
declare module 'moment/locale/mk.js' {
  declare module.exports: $Exports<'moment/locale/mk'>;
}
declare module 'moment/locale/ml.js' {
  declare module.exports: $Exports<'moment/locale/ml'>;
}
declare module 'moment/locale/mn.js' {
  declare module.exports: $Exports<'moment/locale/mn'>;
}
declare module 'moment/locale/mr.js' {
  declare module.exports: $Exports<'moment/locale/mr'>;
}
declare module 'moment/locale/ms-my.js' {
  declare module.exports: $Exports<'moment/locale/ms-my'>;
}
declare module 'moment/locale/ms.js' {
  declare module.exports: $Exports<'moment/locale/ms'>;
}
declare module 'moment/locale/mt.js' {
  declare module.exports: $Exports<'moment/locale/mt'>;
}
declare module 'moment/locale/my.js' {
  declare module.exports: $Exports<'moment/locale/my'>;
}
declare module 'moment/locale/nb.js' {
  declare module.exports: $Exports<'moment/locale/nb'>;
}
declare module 'moment/locale/ne.js' {
  declare module.exports: $Exports<'moment/locale/ne'>;
}
declare module 'moment/locale/nl-be.js' {
  declare module.exports: $Exports<'moment/locale/nl-be'>;
}
declare module 'moment/locale/nl.js' {
  declare module.exports: $Exports<'moment/locale/nl'>;
}
declare module 'moment/locale/nn.js' {
  declare module.exports: $Exports<'moment/locale/nn'>;
}
declare module 'moment/locale/pa-in.js' {
  declare module.exports: $Exports<'moment/locale/pa-in'>;
}
declare module 'moment/locale/pl.js' {
  declare module.exports: $Exports<'moment/locale/pl'>;
}
declare module 'moment/locale/pt-br.js' {
  declare module.exports: $Exports<'moment/locale/pt-br'>;
}
declare module 'moment/locale/pt.js' {
  declare module.exports: $Exports<'moment/locale/pt'>;
}
declare module 'moment/locale/ro.js' {
  declare module.exports: $Exports<'moment/locale/ro'>;
}
declare module 'moment/locale/ru.js' {
  declare module.exports: $Exports<'moment/locale/ru'>;
}
declare module 'moment/locale/sd.js' {
  declare module.exports: $Exports<'moment/locale/sd'>;
}
declare module 'moment/locale/se.js' {
  declare module.exports: $Exports<'moment/locale/se'>;
}
declare module 'moment/locale/si.js' {
  declare module.exports: $Exports<'moment/locale/si'>;
}
declare module 'moment/locale/sk.js' {
  declare module.exports: $Exports<'moment/locale/sk'>;
}
declare module 'moment/locale/sl.js' {
  declare module.exports: $Exports<'moment/locale/sl'>;
}
declare module 'moment/locale/sq.js' {
  declare module.exports: $Exports<'moment/locale/sq'>;
}
declare module 'moment/locale/sr-cyrl.js' {
  declare module.exports: $Exports<'moment/locale/sr-cyrl'>;
}
declare module 'moment/locale/sr.js' {
  declare module.exports: $Exports<'moment/locale/sr'>;
}
declare module 'moment/locale/ss.js' {
  declare module.exports: $Exports<'moment/locale/ss'>;
}
declare module 'moment/locale/sv.js' {
  declare module.exports: $Exports<'moment/locale/sv'>;
}
declare module 'moment/locale/sw.js' {
  declare module.exports: $Exports<'moment/locale/sw'>;
}
declare module 'moment/locale/ta.js' {
  declare module.exports: $Exports<'moment/locale/ta'>;
}
declare module 'moment/locale/te.js' {
  declare module.exports: $Exports<'moment/locale/te'>;
}
declare module 'moment/locale/tet.js' {
  declare module.exports: $Exports<'moment/locale/tet'>;
}
declare module 'moment/locale/tg.js' {
  declare module.exports: $Exports<'moment/locale/tg'>;
}
declare module 'moment/locale/th.js' {
  declare module.exports: $Exports<'moment/locale/th'>;
}
declare module 'moment/locale/tl-ph.js' {
  declare module.exports: $Exports<'moment/locale/tl-ph'>;
}
declare module 'moment/locale/tlh.js' {
  declare module.exports: $Exports<'moment/locale/tlh'>;
}
declare module 'moment/locale/tr.js' {
  declare module.exports: $Exports<'moment/locale/tr'>;
}
declare module 'moment/locale/tzl.js' {
  declare module.exports: $Exports<'moment/locale/tzl'>;
}
declare module 'moment/locale/tzm-latn.js' {
  declare module.exports: $Exports<'moment/locale/tzm-latn'>;
}
declare module 'moment/locale/tzm.js' {
  declare module.exports: $Exports<'moment/locale/tzm'>;
}
declare module 'moment/locale/ug-cn.js' {
  declare module.exports: $Exports<'moment/locale/ug-cn'>;
}
declare module 'moment/locale/uk.js' {
  declare module.exports: $Exports<'moment/locale/uk'>;
}
declare module 'moment/locale/ur.js' {
  declare module.exports: $Exports<'moment/locale/ur'>;
}
declare module 'moment/locale/uz-latn.js' {
  declare module.exports: $Exports<'moment/locale/uz-latn'>;
}
declare module 'moment/locale/uz.js' {
  declare module.exports: $Exports<'moment/locale/uz'>;
}
declare module 'moment/locale/vi.js' {
  declare module.exports: $Exports<'moment/locale/vi'>;
}
declare module 'moment/locale/x-pseudo.js' {
  declare module.exports: $Exports<'moment/locale/x-pseudo'>;
}
declare module 'moment/locale/yo.js' {
  declare module.exports: $Exports<'moment/locale/yo'>;
}
declare module 'moment/locale/zh-cn.js' {
  declare module.exports: $Exports<'moment/locale/zh-cn'>;
}
declare module 'moment/locale/zh-hk.js' {
  declare module.exports: $Exports<'moment/locale/zh-hk'>;
}
declare module 'moment/locale/zh-tw.js' {
  declare module.exports: $Exports<'moment/locale/zh-tw'>;
}
declare module 'moment/min/locales.js' {
  declare module.exports: $Exports<'moment/min/locales'>;
}
declare module 'moment/min/locales.min.js' {
  declare module.exports: $Exports<'moment/min/locales.min'>;
}
declare module 'moment/min/moment-with-locales.js' {
  declare module.exports: $Exports<'moment/min/moment-with-locales'>;
}
declare module 'moment/min/moment-with-locales.min.js' {
  declare module.exports: $Exports<'moment/min/moment-with-locales.min'>;
}
declare module 'moment/min/moment.min.js' {
  declare module.exports: $Exports<'moment/min/moment.min'>;
}
declare module 'moment/moment.js' {
  declare module.exports: $Exports<'moment/moment'>;
}
declare module 'moment/package.js' {
  declare module.exports: $Exports<'moment/package'>;
}
declare module 'moment/src/lib/create/check-overflow.js' {
  declare module.exports: $Exports<'moment/src/lib/create/check-overflow'>;
}
declare module 'moment/src/lib/create/date-from-array.js' {
  declare module.exports: $Exports<'moment/src/lib/create/date-from-array'>;
}
declare module 'moment/src/lib/create/from-anything.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-anything'>;
}
declare module 'moment/src/lib/create/from-array.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-array'>;
}
declare module 'moment/src/lib/create/from-object.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-object'>;
}
declare module 'moment/src/lib/create/from-string-and-array.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-string-and-array'>;
}
declare module 'moment/src/lib/create/from-string-and-format.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-string-and-format'>;
}
declare module 'moment/src/lib/create/from-string.js' {
  declare module.exports: $Exports<'moment/src/lib/create/from-string'>;
}
declare module 'moment/src/lib/create/local.js' {
  declare module.exports: $Exports<'moment/src/lib/create/local'>;
}
declare module 'moment/src/lib/create/parsing-flags.js' {
  declare module.exports: $Exports<'moment/src/lib/create/parsing-flags'>;
}
declare module 'moment/src/lib/create/utc.js' {
  declare module.exports: $Exports<'moment/src/lib/create/utc'>;
}
declare module 'moment/src/lib/create/valid.js' {
  declare module.exports: $Exports<'moment/src/lib/create/valid'>;
}
declare module 'moment/src/lib/duration/abs.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/abs'>;
}
declare module 'moment/src/lib/duration/add-subtract.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/add-subtract'>;
}
declare module 'moment/src/lib/duration/as.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/as'>;
}
declare module 'moment/src/lib/duration/bubble.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/bubble'>;
}
declare module 'moment/src/lib/duration/clone.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/clone'>;
}
declare module 'moment/src/lib/duration/constructor.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/constructor'>;
}
declare module 'moment/src/lib/duration/create.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/create'>;
}
declare module 'moment/src/lib/duration/duration.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/duration'>;
}
declare module 'moment/src/lib/duration/get.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/get'>;
}
declare module 'moment/src/lib/duration/humanize.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/humanize'>;
}
declare module 'moment/src/lib/duration/iso-string.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/iso-string'>;
}
declare module 'moment/src/lib/duration/prototype.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/prototype'>;
}
declare module 'moment/src/lib/duration/valid.js' {
  declare module.exports: $Exports<'moment/src/lib/duration/valid'>;
}
declare module 'moment/src/lib/format/format.js' {
  declare module.exports: $Exports<'moment/src/lib/format/format'>;
}
declare module 'moment/src/lib/locale/base-config.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/base-config'>;
}
declare module 'moment/src/lib/locale/calendar.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/calendar'>;
}
declare module 'moment/src/lib/locale/constructor.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/constructor'>;
}
declare module 'moment/src/lib/locale/en.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/en'>;
}
declare module 'moment/src/lib/locale/formats.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/formats'>;
}
declare module 'moment/src/lib/locale/invalid.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/invalid'>;
}
declare module 'moment/src/lib/locale/lists.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/lists'>;
}
declare module 'moment/src/lib/locale/locale.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/locale'>;
}
declare module 'moment/src/lib/locale/locales.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/locales'>;
}
declare module 'moment/src/lib/locale/ordinal.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/ordinal'>;
}
declare module 'moment/src/lib/locale/pre-post-format.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/pre-post-format'>;
}
declare module 'moment/src/lib/locale/prototype.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/prototype'>;
}
declare module 'moment/src/lib/locale/relative.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/relative'>;
}
declare module 'moment/src/lib/locale/set.js' {
  declare module.exports: $Exports<'moment/src/lib/locale/set'>;
}
declare module 'moment/src/lib/moment/add-subtract.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/add-subtract'>;
}
declare module 'moment/src/lib/moment/calendar.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/calendar'>;
}
declare module 'moment/src/lib/moment/clone.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/clone'>;
}
declare module 'moment/src/lib/moment/compare.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/compare'>;
}
declare module 'moment/src/lib/moment/constructor.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/constructor'>;
}
declare module 'moment/src/lib/moment/creation-data.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/creation-data'>;
}
declare module 'moment/src/lib/moment/diff.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/diff'>;
}
declare module 'moment/src/lib/moment/format.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/format'>;
}
declare module 'moment/src/lib/moment/from.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/from'>;
}
declare module 'moment/src/lib/moment/get-set.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/get-set'>;
}
declare module 'moment/src/lib/moment/locale.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/locale'>;
}
declare module 'moment/src/lib/moment/min-max.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/min-max'>;
}
declare module 'moment/src/lib/moment/moment.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/moment'>;
}
declare module 'moment/src/lib/moment/now.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/now'>;
}
declare module 'moment/src/lib/moment/prototype.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/prototype'>;
}
declare module 'moment/src/lib/moment/start-end-of.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/start-end-of'>;
}
declare module 'moment/src/lib/moment/to-type.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/to-type'>;
}
declare module 'moment/src/lib/moment/to.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/to'>;
}
declare module 'moment/src/lib/moment/valid.js' {
  declare module.exports: $Exports<'moment/src/lib/moment/valid'>;
}
declare module 'moment/src/lib/parse/regex.js' {
  declare module.exports: $Exports<'moment/src/lib/parse/regex'>;
}
declare module 'moment/src/lib/parse/token.js' {
  declare module.exports: $Exports<'moment/src/lib/parse/token'>;
}
declare module 'moment/src/lib/units/aliases.js' {
  declare module.exports: $Exports<'moment/src/lib/units/aliases'>;
}
declare module 'moment/src/lib/units/constants.js' {
  declare module.exports: $Exports<'moment/src/lib/units/constants'>;
}
declare module 'moment/src/lib/units/day-of-month.js' {
  declare module.exports: $Exports<'moment/src/lib/units/day-of-month'>;
}
declare module 'moment/src/lib/units/day-of-week.js' {
  declare module.exports: $Exports<'moment/src/lib/units/day-of-week'>;
}
declare module 'moment/src/lib/units/day-of-year.js' {
  declare module.exports: $Exports<'moment/src/lib/units/day-of-year'>;
}
declare module 'moment/src/lib/units/hour.js' {
  declare module.exports: $Exports<'moment/src/lib/units/hour'>;
}
declare module 'moment/src/lib/units/millisecond.js' {
  declare module.exports: $Exports<'moment/src/lib/units/millisecond'>;
}
declare module 'moment/src/lib/units/minute.js' {
  declare module.exports: $Exports<'moment/src/lib/units/minute'>;
}
declare module 'moment/src/lib/units/month.js' {
  declare module.exports: $Exports<'moment/src/lib/units/month'>;
}
declare module 'moment/src/lib/units/offset.js' {
  declare module.exports: $Exports<'moment/src/lib/units/offset'>;
}
declare module 'moment/src/lib/units/priorities.js' {
  declare module.exports: $Exports<'moment/src/lib/units/priorities'>;
}
declare module 'moment/src/lib/units/quarter.js' {
  declare module.exports: $Exports<'moment/src/lib/units/quarter'>;
}
declare module 'moment/src/lib/units/second.js' {
  declare module.exports: $Exports<'moment/src/lib/units/second'>;
}
declare module 'moment/src/lib/units/timestamp.js' {
  declare module.exports: $Exports<'moment/src/lib/units/timestamp'>;
}
declare module 'moment/src/lib/units/timezone.js' {
  declare module.exports: $Exports<'moment/src/lib/units/timezone'>;
}
declare module 'moment/src/lib/units/units.js' {
  declare module.exports: $Exports<'moment/src/lib/units/units'>;
}
declare module 'moment/src/lib/units/week-calendar-utils.js' {
  declare module.exports: $Exports<'moment/src/lib/units/week-calendar-utils'>;
}
declare module 'moment/src/lib/units/week-year.js' {
  declare module.exports: $Exports<'moment/src/lib/units/week-year'>;
}
declare module 'moment/src/lib/units/week.js' {
  declare module.exports: $Exports<'moment/src/lib/units/week'>;
}
declare module 'moment/src/lib/units/year.js' {
  declare module.exports: $Exports<'moment/src/lib/units/year'>;
}
declare module 'moment/src/lib/utils/abs-ceil.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/abs-ceil'>;
}
declare module 'moment/src/lib/utils/abs-floor.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/abs-floor'>;
}
declare module 'moment/src/lib/utils/abs-round.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/abs-round'>;
}
declare module 'moment/src/lib/utils/compare-arrays.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/compare-arrays'>;
}
declare module 'moment/src/lib/utils/defaults.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/defaults'>;
}
declare module 'moment/src/lib/utils/deprecate.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/deprecate'>;
}
declare module 'moment/src/lib/utils/extend.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/extend'>;
}
declare module 'moment/src/lib/utils/has-own-prop.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/has-own-prop'>;
}
declare module 'moment/src/lib/utils/hooks.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/hooks'>;
}
declare module 'moment/src/lib/utils/index-of.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/index-of'>;
}
declare module 'moment/src/lib/utils/is-array.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-array'>;
}
declare module 'moment/src/lib/utils/is-date.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-date'>;
}
declare module 'moment/src/lib/utils/is-function.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-function'>;
}
declare module 'moment/src/lib/utils/is-number.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-number'>;
}
declare module 'moment/src/lib/utils/is-object-empty.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-object-empty'>;
}
declare module 'moment/src/lib/utils/is-object.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-object'>;
}
declare module 'moment/src/lib/utils/is-undefined.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/is-undefined'>;
}
declare module 'moment/src/lib/utils/keys.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/keys'>;
}
declare module 'moment/src/lib/utils/map.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/map'>;
}
declare module 'moment/src/lib/utils/mod.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/mod'>;
}
declare module 'moment/src/lib/utils/some.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/some'>;
}
declare module 'moment/src/lib/utils/to-int.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/to-int'>;
}
declare module 'moment/src/lib/utils/zero-fill.js' {
  declare module.exports: $Exports<'moment/src/lib/utils/zero-fill'>;
}
declare module 'moment/src/locale/af.js' {
  declare module.exports: $Exports<'moment/src/locale/af'>;
}
declare module 'moment/src/locale/ar-dz.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-dz'>;
}
declare module 'moment/src/locale/ar-kw.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-kw'>;
}
declare module 'moment/src/locale/ar-ly.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-ly'>;
}
declare module 'moment/src/locale/ar-ma.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-ma'>;
}
declare module 'moment/src/locale/ar-sa.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-sa'>;
}
declare module 'moment/src/locale/ar-tn.js' {
  declare module.exports: $Exports<'moment/src/locale/ar-tn'>;
}
declare module 'moment/src/locale/ar.js' {
  declare module.exports: $Exports<'moment/src/locale/ar'>;
}
declare module 'moment/src/locale/az.js' {
  declare module.exports: $Exports<'moment/src/locale/az'>;
}
declare module 'moment/src/locale/be.js' {
  declare module.exports: $Exports<'moment/src/locale/be'>;
}
declare module 'moment/src/locale/bg.js' {
  declare module.exports: $Exports<'moment/src/locale/bg'>;
}
declare module 'moment/src/locale/bm.js' {
  declare module.exports: $Exports<'moment/src/locale/bm'>;
}
declare module 'moment/src/locale/bn.js' {
  declare module.exports: $Exports<'moment/src/locale/bn'>;
}
declare module 'moment/src/locale/bo.js' {
  declare module.exports: $Exports<'moment/src/locale/bo'>;
}
declare module 'moment/src/locale/br.js' {
  declare module.exports: $Exports<'moment/src/locale/br'>;
}
declare module 'moment/src/locale/bs.js' {
  declare module.exports: $Exports<'moment/src/locale/bs'>;
}
declare module 'moment/src/locale/ca.js' {
  declare module.exports: $Exports<'moment/src/locale/ca'>;
}
declare module 'moment/src/locale/cs.js' {
  declare module.exports: $Exports<'moment/src/locale/cs'>;
}
declare module 'moment/src/locale/cv.js' {
  declare module.exports: $Exports<'moment/src/locale/cv'>;
}
declare module 'moment/src/locale/cy.js' {
  declare module.exports: $Exports<'moment/src/locale/cy'>;
}
declare module 'moment/src/locale/da.js' {
  declare module.exports: $Exports<'moment/src/locale/da'>;
}
declare module 'moment/src/locale/de-at.js' {
  declare module.exports: $Exports<'moment/src/locale/de-at'>;
}
declare module 'moment/src/locale/de-ch.js' {
  declare module.exports: $Exports<'moment/src/locale/de-ch'>;
}
declare module 'moment/src/locale/de.js' {
  declare module.exports: $Exports<'moment/src/locale/de'>;
}
declare module 'moment/src/locale/dv.js' {
  declare module.exports: $Exports<'moment/src/locale/dv'>;
}
declare module 'moment/src/locale/el.js' {
  declare module.exports: $Exports<'moment/src/locale/el'>;
}
declare module 'moment/src/locale/en-au.js' {
  declare module.exports: $Exports<'moment/src/locale/en-au'>;
}
declare module 'moment/src/locale/en-ca.js' {
  declare module.exports: $Exports<'moment/src/locale/en-ca'>;
}
declare module 'moment/src/locale/en-gb.js' {
  declare module.exports: $Exports<'moment/src/locale/en-gb'>;
}
declare module 'moment/src/locale/en-ie.js' {
  declare module.exports: $Exports<'moment/src/locale/en-ie'>;
}
declare module 'moment/src/locale/en-il.js' {
  declare module.exports: $Exports<'moment/src/locale/en-il'>;
}
declare module 'moment/src/locale/en-nz.js' {
  declare module.exports: $Exports<'moment/src/locale/en-nz'>;
}
declare module 'moment/src/locale/eo.js' {
  declare module.exports: $Exports<'moment/src/locale/eo'>;
}
declare module 'moment/src/locale/es-do.js' {
  declare module.exports: $Exports<'moment/src/locale/es-do'>;
}
declare module 'moment/src/locale/es-us.js' {
  declare module.exports: $Exports<'moment/src/locale/es-us'>;
}
declare module 'moment/src/locale/es.js' {
  declare module.exports: $Exports<'moment/src/locale/es'>;
}
declare module 'moment/src/locale/et.js' {
  declare module.exports: $Exports<'moment/src/locale/et'>;
}
declare module 'moment/src/locale/eu.js' {
  declare module.exports: $Exports<'moment/src/locale/eu'>;
}
declare module 'moment/src/locale/fa.js' {
  declare module.exports: $Exports<'moment/src/locale/fa'>;
}
declare module 'moment/src/locale/fi.js' {
  declare module.exports: $Exports<'moment/src/locale/fi'>;
}
declare module 'moment/src/locale/fo.js' {
  declare module.exports: $Exports<'moment/src/locale/fo'>;
}
declare module 'moment/src/locale/fr-ca.js' {
  declare module.exports: $Exports<'moment/src/locale/fr-ca'>;
}
declare module 'moment/src/locale/fr-ch.js' {
  declare module.exports: $Exports<'moment/src/locale/fr-ch'>;
}
declare module 'moment/src/locale/fr.js' {
  declare module.exports: $Exports<'moment/src/locale/fr'>;
}
declare module 'moment/src/locale/fy.js' {
  declare module.exports: $Exports<'moment/src/locale/fy'>;
}
declare module 'moment/src/locale/gd.js' {
  declare module.exports: $Exports<'moment/src/locale/gd'>;
}
declare module 'moment/src/locale/gl.js' {
  declare module.exports: $Exports<'moment/src/locale/gl'>;
}
declare module 'moment/src/locale/gom-latn.js' {
  declare module.exports: $Exports<'moment/src/locale/gom-latn'>;
}
declare module 'moment/src/locale/gu.js' {
  declare module.exports: $Exports<'moment/src/locale/gu'>;
}
declare module 'moment/src/locale/he.js' {
  declare module.exports: $Exports<'moment/src/locale/he'>;
}
declare module 'moment/src/locale/hi.js' {
  declare module.exports: $Exports<'moment/src/locale/hi'>;
}
declare module 'moment/src/locale/hr.js' {
  declare module.exports: $Exports<'moment/src/locale/hr'>;
}
declare module 'moment/src/locale/hu.js' {
  declare module.exports: $Exports<'moment/src/locale/hu'>;
}
declare module 'moment/src/locale/hy-am.js' {
  declare module.exports: $Exports<'moment/src/locale/hy-am'>;
}
declare module 'moment/src/locale/id.js' {
  declare module.exports: $Exports<'moment/src/locale/id'>;
}
declare module 'moment/src/locale/is.js' {
  declare module.exports: $Exports<'moment/src/locale/is'>;
}
declare module 'moment/src/locale/it.js' {
  declare module.exports: $Exports<'moment/src/locale/it'>;
}
declare module 'moment/src/locale/ja.js' {
  declare module.exports: $Exports<'moment/src/locale/ja'>;
}
declare module 'moment/src/locale/jv.js' {
  declare module.exports: $Exports<'moment/src/locale/jv'>;
}
declare module 'moment/src/locale/ka.js' {
  declare module.exports: $Exports<'moment/src/locale/ka'>;
}
declare module 'moment/src/locale/kk.js' {
  declare module.exports: $Exports<'moment/src/locale/kk'>;
}
declare module 'moment/src/locale/km.js' {
  declare module.exports: $Exports<'moment/src/locale/km'>;
}
declare module 'moment/src/locale/kn.js' {
  declare module.exports: $Exports<'moment/src/locale/kn'>;
}
declare module 'moment/src/locale/ko.js' {
  declare module.exports: $Exports<'moment/src/locale/ko'>;
}
declare module 'moment/src/locale/ky.js' {
  declare module.exports: $Exports<'moment/src/locale/ky'>;
}
declare module 'moment/src/locale/lb.js' {
  declare module.exports: $Exports<'moment/src/locale/lb'>;
}
declare module 'moment/src/locale/lo.js' {
  declare module.exports: $Exports<'moment/src/locale/lo'>;
}
declare module 'moment/src/locale/lt.js' {
  declare module.exports: $Exports<'moment/src/locale/lt'>;
}
declare module 'moment/src/locale/lv.js' {
  declare module.exports: $Exports<'moment/src/locale/lv'>;
}
declare module 'moment/src/locale/me.js' {
  declare module.exports: $Exports<'moment/src/locale/me'>;
}
declare module 'moment/src/locale/mi.js' {
  declare module.exports: $Exports<'moment/src/locale/mi'>;
}
declare module 'moment/src/locale/mk.js' {
  declare module.exports: $Exports<'moment/src/locale/mk'>;
}
declare module 'moment/src/locale/ml.js' {
  declare module.exports: $Exports<'moment/src/locale/ml'>;
}
declare module 'moment/src/locale/mn.js' {
  declare module.exports: $Exports<'moment/src/locale/mn'>;
}
declare module 'moment/src/locale/mr.js' {
  declare module.exports: $Exports<'moment/src/locale/mr'>;
}
declare module 'moment/src/locale/ms-my.js' {
  declare module.exports: $Exports<'moment/src/locale/ms-my'>;
}
declare module 'moment/src/locale/ms.js' {
  declare module.exports: $Exports<'moment/src/locale/ms'>;
}
declare module 'moment/src/locale/mt.js' {
  declare module.exports: $Exports<'moment/src/locale/mt'>;
}
declare module 'moment/src/locale/my.js' {
  declare module.exports: $Exports<'moment/src/locale/my'>;
}
declare module 'moment/src/locale/nb.js' {
  declare module.exports: $Exports<'moment/src/locale/nb'>;
}
declare module 'moment/src/locale/ne.js' {
  declare module.exports: $Exports<'moment/src/locale/ne'>;
}
declare module 'moment/src/locale/nl-be.js' {
  declare module.exports: $Exports<'moment/src/locale/nl-be'>;
}
declare module 'moment/src/locale/nl.js' {
  declare module.exports: $Exports<'moment/src/locale/nl'>;
}
declare module 'moment/src/locale/nn.js' {
  declare module.exports: $Exports<'moment/src/locale/nn'>;
}
declare module 'moment/src/locale/pa-in.js' {
  declare module.exports: $Exports<'moment/src/locale/pa-in'>;
}
declare module 'moment/src/locale/pl.js' {
  declare module.exports: $Exports<'moment/src/locale/pl'>;
}
declare module 'moment/src/locale/pt-br.js' {
  declare module.exports: $Exports<'moment/src/locale/pt-br'>;
}
declare module 'moment/src/locale/pt.js' {
  declare module.exports: $Exports<'moment/src/locale/pt'>;
}
declare module 'moment/src/locale/ro.js' {
  declare module.exports: $Exports<'moment/src/locale/ro'>;
}
declare module 'moment/src/locale/ru.js' {
  declare module.exports: $Exports<'moment/src/locale/ru'>;
}
declare module 'moment/src/locale/sd.js' {
  declare module.exports: $Exports<'moment/src/locale/sd'>;
}
declare module 'moment/src/locale/se.js' {
  declare module.exports: $Exports<'moment/src/locale/se'>;
}
declare module 'moment/src/locale/si.js' {
  declare module.exports: $Exports<'moment/src/locale/si'>;
}
declare module 'moment/src/locale/sk.js' {
  declare module.exports: $Exports<'moment/src/locale/sk'>;
}
declare module 'moment/src/locale/sl.js' {
  declare module.exports: $Exports<'moment/src/locale/sl'>;
}
declare module 'moment/src/locale/sq.js' {
  declare module.exports: $Exports<'moment/src/locale/sq'>;
}
declare module 'moment/src/locale/sr-cyrl.js' {
  declare module.exports: $Exports<'moment/src/locale/sr-cyrl'>;
}
declare module 'moment/src/locale/sr.js' {
  declare module.exports: $Exports<'moment/src/locale/sr'>;
}
declare module 'moment/src/locale/ss.js' {
  declare module.exports: $Exports<'moment/src/locale/ss'>;
}
declare module 'moment/src/locale/sv.js' {
  declare module.exports: $Exports<'moment/src/locale/sv'>;
}
declare module 'moment/src/locale/sw.js' {
  declare module.exports: $Exports<'moment/src/locale/sw'>;
}
declare module 'moment/src/locale/ta.js' {
  declare module.exports: $Exports<'moment/src/locale/ta'>;
}
declare module 'moment/src/locale/te.js' {
  declare module.exports: $Exports<'moment/src/locale/te'>;
}
declare module 'moment/src/locale/tet.js' {
  declare module.exports: $Exports<'moment/src/locale/tet'>;
}
declare module 'moment/src/locale/tg.js' {
  declare module.exports: $Exports<'moment/src/locale/tg'>;
}
declare module 'moment/src/locale/th.js' {
  declare module.exports: $Exports<'moment/src/locale/th'>;
}
declare module 'moment/src/locale/tl-ph.js' {
  declare module.exports: $Exports<'moment/src/locale/tl-ph'>;
}
declare module 'moment/src/locale/tlh.js' {
  declare module.exports: $Exports<'moment/src/locale/tlh'>;
}
declare module 'moment/src/locale/tr.js' {
  declare module.exports: $Exports<'moment/src/locale/tr'>;
}
declare module 'moment/src/locale/tzl.js' {
  declare module.exports: $Exports<'moment/src/locale/tzl'>;
}
declare module 'moment/src/locale/tzm-latn.js' {
  declare module.exports: $Exports<'moment/src/locale/tzm-latn'>;
}
declare module 'moment/src/locale/tzm.js' {
  declare module.exports: $Exports<'moment/src/locale/tzm'>;
}
declare module 'moment/src/locale/ug-cn.js' {
  declare module.exports: $Exports<'moment/src/locale/ug-cn'>;
}
declare module 'moment/src/locale/uk.js' {
  declare module.exports: $Exports<'moment/src/locale/uk'>;
}
declare module 'moment/src/locale/ur.js' {
  declare module.exports: $Exports<'moment/src/locale/ur'>;
}
declare module 'moment/src/locale/uz-latn.js' {
  declare module.exports: $Exports<'moment/src/locale/uz-latn'>;
}
declare module 'moment/src/locale/uz.js' {
  declare module.exports: $Exports<'moment/src/locale/uz'>;
}
declare module 'moment/src/locale/vi.js' {
  declare module.exports: $Exports<'moment/src/locale/vi'>;
}
declare module 'moment/src/locale/x-pseudo.js' {
  declare module.exports: $Exports<'moment/src/locale/x-pseudo'>;
}
declare module 'moment/src/locale/yo.js' {
  declare module.exports: $Exports<'moment/src/locale/yo'>;
}
declare module 'moment/src/locale/zh-cn.js' {
  declare module.exports: $Exports<'moment/src/locale/zh-cn'>;
}
declare module 'moment/src/locale/zh-hk.js' {
  declare module.exports: $Exports<'moment/src/locale/zh-hk'>;
}
declare module 'moment/src/locale/zh-tw.js' {
  declare module.exports: $Exports<'moment/src/locale/zh-tw'>;
}
declare module 'moment/src/moment.js' {
  declare module.exports: $Exports<'moment/src/moment'>;
}
