// flow-typed signature: 721181963edc4ac2e897a919b3357c69
// flow-typed version: <<STUB>>/rsuite-notification_v~3.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsuite-notification'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsuite-notification' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsuite-notification/lib/component/Alert' {
  declare module.exports: any;
}

declare module 'rsuite-notification/lib/component/Notify' {
  declare module.exports: any;
}

declare module 'rsuite-notification/lib/constants/index' {
  declare module.exports: any;
}

declare module 'rsuite-notification/lib/core' {
  declare module.exports: any;
}

declare module 'rsuite-notification/lib/index' {
  declare module.exports: any;
}

declare module 'rsuite-notification/lib/notice' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsuite-notification/lib/component/Alert.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/component/Alert'>;
}
declare module 'rsuite-notification/lib/component/Notify.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/component/Notify'>;
}
declare module 'rsuite-notification/lib/constants/index.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/constants/index'>;
}
declare module 'rsuite-notification/lib/core.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/core'>;
}
declare module 'rsuite-notification/lib/index.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/index'>;
}
declare module 'rsuite-notification/lib/notice.js' {
  declare module.exports: $Exports<'rsuite-notification/lib/notice'>;
}
