// flow-typed signature: 13054be4d9d3bdfe267f0e2ab065caca
// flow-typed version: <<STUB>>/rsuite-intl_v~1.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsuite-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsuite-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsuite-intl/lib/FormattedMessage' {
  declare module.exports: any;
}

declare module 'rsuite-intl/lib/index' {
  declare module.exports: any;
}

declare module 'rsuite-intl/lib/IntlProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsuite-intl/lib/FormattedMessage.js' {
  declare module.exports: $Exports<'rsuite-intl/lib/FormattedMessage'>;
}
declare module 'rsuite-intl/lib/index.js' {
  declare module.exports: $Exports<'rsuite-intl/lib/index'>;
}
declare module 'rsuite-intl/lib/IntlProvider.js' {
  declare module.exports: $Exports<'rsuite-intl/lib/IntlProvider'>;
}
