// flow-typed signature: 3d003bf6c12c7b0957bd6269e5173839
// flow-typed version: <<STUB>>/rsuite-table_v~3.0.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsuite-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsuite-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsuite-table/lib/Cell' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/CellGroup' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/Column' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/ColumnResizeHandler' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/constants' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/HeaderCell' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/index' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/Row' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/Scrollbar' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/Table' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/colSpanCells' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/getTotalByColumns' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/getUnhandledProps' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/index' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/prefix' {
  declare module.exports: any;
}

declare module 'rsuite-table/lib/utils/toggleClass' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/Cell' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/CellGroup' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/Column' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/ColumnResizeHandler' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/constants' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/HeaderCell' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/index' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/Row' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/Scrollbar' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/Table' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/colSpanCells' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/getTotalByColumns' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/getUnhandledProps' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/index' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/prefix' {
  declare module.exports: any;
}

declare module 'rsuite-table/src/utils/toggleClass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsuite-table/lib/Cell.js' {
  declare module.exports: $Exports<'rsuite-table/lib/Cell'>;
}
declare module 'rsuite-table/lib/CellGroup.js' {
  declare module.exports: $Exports<'rsuite-table/lib/CellGroup'>;
}
declare module 'rsuite-table/lib/Column.js' {
  declare module.exports: $Exports<'rsuite-table/lib/Column'>;
}
declare module 'rsuite-table/lib/ColumnResizeHandler.js' {
  declare module.exports: $Exports<'rsuite-table/lib/ColumnResizeHandler'>;
}
declare module 'rsuite-table/lib/constants.js' {
  declare module.exports: $Exports<'rsuite-table/lib/constants'>;
}
declare module 'rsuite-table/lib/HeaderCell.js' {
  declare module.exports: $Exports<'rsuite-table/lib/HeaderCell'>;
}
declare module 'rsuite-table/lib/index.js' {
  declare module.exports: $Exports<'rsuite-table/lib/index'>;
}
declare module 'rsuite-table/lib/Row.js' {
  declare module.exports: $Exports<'rsuite-table/lib/Row'>;
}
declare module 'rsuite-table/lib/Scrollbar.js' {
  declare module.exports: $Exports<'rsuite-table/lib/Scrollbar'>;
}
declare module 'rsuite-table/lib/Table.js' {
  declare module.exports: $Exports<'rsuite-table/lib/Table'>;
}
declare module 'rsuite-table/lib/utils/colSpanCells.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/colSpanCells'>;
}
declare module 'rsuite-table/lib/utils/getTotalByColumns.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/getTotalByColumns'>;
}
declare module 'rsuite-table/lib/utils/getUnhandledProps.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/getUnhandledProps'>;
}
declare module 'rsuite-table/lib/utils/index.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/index'>;
}
declare module 'rsuite-table/lib/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/isNullOrUndefined'>;
}
declare module 'rsuite-table/lib/utils/prefix.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/prefix'>;
}
declare module 'rsuite-table/lib/utils/toggleClass.js' {
  declare module.exports: $Exports<'rsuite-table/lib/utils/toggleClass'>;
}
declare module 'rsuite-table/src/Cell.js' {
  declare module.exports: $Exports<'rsuite-table/src/Cell'>;
}
declare module 'rsuite-table/src/CellGroup.js' {
  declare module.exports: $Exports<'rsuite-table/src/CellGroup'>;
}
declare module 'rsuite-table/src/Column.js' {
  declare module.exports: $Exports<'rsuite-table/src/Column'>;
}
declare module 'rsuite-table/src/ColumnResizeHandler.js' {
  declare module.exports: $Exports<'rsuite-table/src/ColumnResizeHandler'>;
}
declare module 'rsuite-table/src/constants.js' {
  declare module.exports: $Exports<'rsuite-table/src/constants'>;
}
declare module 'rsuite-table/src/HeaderCell.js' {
  declare module.exports: $Exports<'rsuite-table/src/HeaderCell'>;
}
declare module 'rsuite-table/src/index.js' {
  declare module.exports: $Exports<'rsuite-table/src/index'>;
}
declare module 'rsuite-table/src/Row.js' {
  declare module.exports: $Exports<'rsuite-table/src/Row'>;
}
declare module 'rsuite-table/src/Scrollbar.js' {
  declare module.exports: $Exports<'rsuite-table/src/Scrollbar'>;
}
declare module 'rsuite-table/src/Table.js' {
  declare module.exports: $Exports<'rsuite-table/src/Table'>;
}
declare module 'rsuite-table/src/utils/colSpanCells.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/colSpanCells'>;
}
declare module 'rsuite-table/src/utils/getTotalByColumns.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/getTotalByColumns'>;
}
declare module 'rsuite-table/src/utils/getUnhandledProps.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/getUnhandledProps'>;
}
declare module 'rsuite-table/src/utils/index.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/index'>;
}
declare module 'rsuite-table/src/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/isNullOrUndefined'>;
}
declare module 'rsuite-table/src/utils/prefix.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/prefix'>;
}
declare module 'rsuite-table/src/utils/toggleClass.js' {
  declare module.exports: $Exports<'rsuite-table/src/utils/toggleClass'>;
}
