// flow-typed signature: 69f64e32a5af1b4b740b401831609fa7
// flow-typed version: <<STUB>>/rsuite-schema_v~0.0.12/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsuite-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsuite-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsuite-schema/lib/ArrayType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/BooleanType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/DateType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/index' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/NumberType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/ObjectType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/Schema' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/StringType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/Type' {
  declare module.exports: any;
}

declare module 'rsuite-schema/lib/types' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/ArrayType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/BooleanType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/DateType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/index' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/NumberType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/ObjectType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/Schema' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/StringType' {
  declare module.exports: any;
}

declare module 'rsuite-schema/src/Type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsuite-schema/lib/ArrayType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/ArrayType'>;
}
declare module 'rsuite-schema/lib/BooleanType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/BooleanType'>;
}
declare module 'rsuite-schema/lib/DateType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/DateType'>;
}
declare module 'rsuite-schema/lib/index.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/index'>;
}
declare module 'rsuite-schema/lib/NumberType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/NumberType'>;
}
declare module 'rsuite-schema/lib/ObjectType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/ObjectType'>;
}
declare module 'rsuite-schema/lib/Schema.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/Schema'>;
}
declare module 'rsuite-schema/lib/StringType.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/StringType'>;
}
declare module 'rsuite-schema/lib/Type.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/Type'>;
}
declare module 'rsuite-schema/lib/types.js' {
  declare module.exports: $Exports<'rsuite-schema/lib/types'>;
}
declare module 'rsuite-schema/src/ArrayType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/ArrayType'>;
}
declare module 'rsuite-schema/src/BooleanType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/BooleanType'>;
}
declare module 'rsuite-schema/src/DateType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/DateType'>;
}
declare module 'rsuite-schema/src/index.js' {
  declare module.exports: $Exports<'rsuite-schema/src/index'>;
}
declare module 'rsuite-schema/src/NumberType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/NumberType'>;
}
declare module 'rsuite-schema/src/ObjectType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/ObjectType'>;
}
declare module 'rsuite-schema/src/Schema.js' {
  declare module.exports: $Exports<'rsuite-schema/src/Schema'>;
}
declare module 'rsuite-schema/src/StringType.js' {
  declare module.exports: $Exports<'rsuite-schema/src/StringType'>;
}
declare module 'rsuite-schema/src/Type.js' {
  declare module.exports: $Exports<'rsuite-schema/src/Type'>;
}
