// flow-typed signature: 31b16e559cbb7b3af88d61aab0ef0724
// flow-typed version: <<STUB>>/rsuite-utils_v~1.2.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsuite-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsuite-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsuite-utils/lib/Animation/Collapse' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Animation/Fade' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Animation/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Animation/Transition' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/BaseOverlay' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/LegacyPortal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/Modal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/ModalManager' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/Overlay' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/Portal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/Position' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/RefHolder' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Overlay/RootCloseWrapper' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Picker/constants' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Picker/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Picker/MenuWrapper' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Picker/SearchBar' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/Picker/Toggle' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/copyToClipboard' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/filterNodesOfTree' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/findNodeOfTree' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/getDataGroupBy' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/getUnhandledProps' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/handleMouseOverOut' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/isOneOf' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/overlayPositionUtils' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/prefix' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/reactToString' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/shallowEqualArray' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/tplTransform' {
  declare module.exports: any;
}

declare module 'rsuite-utils/lib/utils/TypeDefinition' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Animation/Collapse' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Animation/Fade' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Animation/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Animation/Transition' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/BaseOverlay' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/LegacyPortal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/Modal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/ModalManager' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/Overlay' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/Portal' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/Position' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/RefHolder' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Overlay/RootCloseWrapper' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Picker/constants' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Picker/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Picker/MenuWrapper' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Picker/SearchBar' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/Picker/Toggle' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/copyToClipboard' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/filterNodesOfTree' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/findNodeOfTree' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/getDataGroupBy' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/getUnhandledProps' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/handleMouseOverOut' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/index' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/isOneOf' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/overlayPositionUtils' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/prefix' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/reactToString' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/shallowEqualArray' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/tplTransform' {
  declare module.exports: any;
}

declare module 'rsuite-utils/src/utils/TypeDefinition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsuite-utils/lib/Animation/Collapse.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Animation/Collapse'>;
}
declare module 'rsuite-utils/lib/Animation/Fade.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Animation/Fade'>;
}
declare module 'rsuite-utils/lib/Animation/index.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Animation/index'>;
}
declare module 'rsuite-utils/lib/Animation/Transition.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Animation/Transition'>;
}
declare module 'rsuite-utils/lib/index.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/index'>;
}
declare module 'rsuite-utils/lib/Overlay/BaseOverlay.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/BaseOverlay'>;
}
declare module 'rsuite-utils/lib/Overlay/index.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/index'>;
}
declare module 'rsuite-utils/lib/Overlay/LegacyPortal.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/LegacyPortal'>;
}
declare module 'rsuite-utils/lib/Overlay/Modal.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/Modal'>;
}
declare module 'rsuite-utils/lib/Overlay/ModalManager.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/ModalManager'>;
}
declare module 'rsuite-utils/lib/Overlay/Overlay.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/Overlay'>;
}
declare module 'rsuite-utils/lib/Overlay/OverlayTrigger.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/OverlayTrigger'>;
}
declare module 'rsuite-utils/lib/Overlay/Portal.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/Portal'>;
}
declare module 'rsuite-utils/lib/Overlay/Position.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/Position'>;
}
declare module 'rsuite-utils/lib/Overlay/RefHolder.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/RefHolder'>;
}
declare module 'rsuite-utils/lib/Overlay/RootCloseWrapper.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Overlay/RootCloseWrapper'>;
}
declare module 'rsuite-utils/lib/Picker/constants.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Picker/constants'>;
}
declare module 'rsuite-utils/lib/Picker/index.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Picker/index'>;
}
declare module 'rsuite-utils/lib/Picker/MenuWrapper.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Picker/MenuWrapper'>;
}
declare module 'rsuite-utils/lib/Picker/SearchBar.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Picker/SearchBar'>;
}
declare module 'rsuite-utils/lib/Picker/Toggle.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/Picker/Toggle'>;
}
declare module 'rsuite-utils/lib/utils/copyToClipboard.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/copyToClipboard'>;
}
declare module 'rsuite-utils/lib/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/createChainedFunction'>;
}
declare module 'rsuite-utils/lib/utils/filterNodesOfTree.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/filterNodesOfTree'>;
}
declare module 'rsuite-utils/lib/utils/findNodeOfTree.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/findNodeOfTree'>;
}
declare module 'rsuite-utils/lib/utils/getDataGroupBy.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/getDataGroupBy'>;
}
declare module 'rsuite-utils/lib/utils/getUnhandledProps.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/getUnhandledProps'>;
}
declare module 'rsuite-utils/lib/utils/handleMouseOverOut.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/handleMouseOverOut'>;
}
declare module 'rsuite-utils/lib/utils/index.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/index'>;
}
declare module 'rsuite-utils/lib/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/isNullOrUndefined'>;
}
declare module 'rsuite-utils/lib/utils/isOneOf.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/isOneOf'>;
}
declare module 'rsuite-utils/lib/utils/overlayPositionUtils.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/overlayPositionUtils'>;
}
declare module 'rsuite-utils/lib/utils/prefix.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/prefix'>;
}
declare module 'rsuite-utils/lib/utils/reactToString.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/reactToString'>;
}
declare module 'rsuite-utils/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/shallowEqual'>;
}
declare module 'rsuite-utils/lib/utils/shallowEqualArray.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/shallowEqualArray'>;
}
declare module 'rsuite-utils/lib/utils/tplTransform.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/tplTransform'>;
}
declare module 'rsuite-utils/lib/utils/TypeDefinition.js' {
  declare module.exports: $Exports<'rsuite-utils/lib/utils/TypeDefinition'>;
}
declare module 'rsuite-utils/src/Animation/Collapse.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Animation/Collapse'>;
}
declare module 'rsuite-utils/src/Animation/Fade.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Animation/Fade'>;
}
declare module 'rsuite-utils/src/Animation/index.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Animation/index'>;
}
declare module 'rsuite-utils/src/Animation/Transition.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Animation/Transition'>;
}
declare module 'rsuite-utils/src/index.js' {
  declare module.exports: $Exports<'rsuite-utils/src/index'>;
}
declare module 'rsuite-utils/src/Overlay/BaseOverlay.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/BaseOverlay'>;
}
declare module 'rsuite-utils/src/Overlay/index.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/index'>;
}
declare module 'rsuite-utils/src/Overlay/LegacyPortal.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/LegacyPortal'>;
}
declare module 'rsuite-utils/src/Overlay/Modal.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/Modal'>;
}
declare module 'rsuite-utils/src/Overlay/ModalManager.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/ModalManager'>;
}
declare module 'rsuite-utils/src/Overlay/Overlay.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/Overlay'>;
}
declare module 'rsuite-utils/src/Overlay/OverlayTrigger.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/OverlayTrigger'>;
}
declare module 'rsuite-utils/src/Overlay/Portal.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/Portal'>;
}
declare module 'rsuite-utils/src/Overlay/Position.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/Position'>;
}
declare module 'rsuite-utils/src/Overlay/RefHolder.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/RefHolder'>;
}
declare module 'rsuite-utils/src/Overlay/RootCloseWrapper.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Overlay/RootCloseWrapper'>;
}
declare module 'rsuite-utils/src/Picker/constants.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Picker/constants'>;
}
declare module 'rsuite-utils/src/Picker/index.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Picker/index'>;
}
declare module 'rsuite-utils/src/Picker/MenuWrapper.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Picker/MenuWrapper'>;
}
declare module 'rsuite-utils/src/Picker/SearchBar.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Picker/SearchBar'>;
}
declare module 'rsuite-utils/src/Picker/Toggle.js' {
  declare module.exports: $Exports<'rsuite-utils/src/Picker/Toggle'>;
}
declare module 'rsuite-utils/src/utils/copyToClipboard.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/copyToClipboard'>;
}
declare module 'rsuite-utils/src/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/createChainedFunction'>;
}
declare module 'rsuite-utils/src/utils/filterNodesOfTree.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/filterNodesOfTree'>;
}
declare module 'rsuite-utils/src/utils/findNodeOfTree.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/findNodeOfTree'>;
}
declare module 'rsuite-utils/src/utils/getDataGroupBy.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/getDataGroupBy'>;
}
declare module 'rsuite-utils/src/utils/getUnhandledProps.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/getUnhandledProps'>;
}
declare module 'rsuite-utils/src/utils/handleMouseOverOut.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/handleMouseOverOut'>;
}
declare module 'rsuite-utils/src/utils/index.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/index'>;
}
declare module 'rsuite-utils/src/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/isNullOrUndefined'>;
}
declare module 'rsuite-utils/src/utils/isOneOf.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/isOneOf'>;
}
declare module 'rsuite-utils/src/utils/overlayPositionUtils.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/overlayPositionUtils'>;
}
declare module 'rsuite-utils/src/utils/prefix.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/prefix'>;
}
declare module 'rsuite-utils/src/utils/reactToString.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/reactToString'>;
}
declare module 'rsuite-utils/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/shallowEqual'>;
}
declare module 'rsuite-utils/src/utils/shallowEqualArray.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/shallowEqualArray'>;
}
declare module 'rsuite-utils/src/utils/tplTransform.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/tplTransform'>;
}
declare module 'rsuite-utils/src/utils/TypeDefinition.js' {
  declare module.exports: $Exports<'rsuite-utils/src/utils/TypeDefinition'>;
}
