// flow-typed signature: 78b8423c422abab219bf4bfd08abaee1
// flow-typed version: <<STUB>>/schema-typed_v~0.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'schema-typed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'schema-typed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'schema-typed/lib/ArrayType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/BooleanType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/DateType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/index' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/NumberType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/ObjectType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/Schema' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/StringType' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/Type' {
  declare module.exports: any;
}

declare module 'schema-typed/lib/types' {
  declare module.exports: any;
}

declare module 'schema-typed/src/ArrayType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/BooleanType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/DateType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/index' {
  declare module.exports: any;
}

declare module 'schema-typed/src/NumberType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/ObjectType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/Schema' {
  declare module.exports: any;
}

declare module 'schema-typed/src/StringType' {
  declare module.exports: any;
}

declare module 'schema-typed/src/Type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'schema-typed/lib/ArrayType.js' {
  declare module.exports: $Exports<'schema-typed/lib/ArrayType'>;
}
declare module 'schema-typed/lib/BooleanType.js' {
  declare module.exports: $Exports<'schema-typed/lib/BooleanType'>;
}
declare module 'schema-typed/lib/DateType.js' {
  declare module.exports: $Exports<'schema-typed/lib/DateType'>;
}
declare module 'schema-typed/lib/index.js' {
  declare module.exports: $Exports<'schema-typed/lib/index'>;
}
declare module 'schema-typed/lib/NumberType.js' {
  declare module.exports: $Exports<'schema-typed/lib/NumberType'>;
}
declare module 'schema-typed/lib/ObjectType.js' {
  declare module.exports: $Exports<'schema-typed/lib/ObjectType'>;
}
declare module 'schema-typed/lib/Schema.js' {
  declare module.exports: $Exports<'schema-typed/lib/Schema'>;
}
declare module 'schema-typed/lib/StringType.js' {
  declare module.exports: $Exports<'schema-typed/lib/StringType'>;
}
declare module 'schema-typed/lib/Type.js' {
  declare module.exports: $Exports<'schema-typed/lib/Type'>;
}
declare module 'schema-typed/lib/types.js' {
  declare module.exports: $Exports<'schema-typed/lib/types'>;
}
declare module 'schema-typed/src/ArrayType.js' {
  declare module.exports: $Exports<'schema-typed/src/ArrayType'>;
}
declare module 'schema-typed/src/BooleanType.js' {
  declare module.exports: $Exports<'schema-typed/src/BooleanType'>;
}
declare module 'schema-typed/src/DateType.js' {
  declare module.exports: $Exports<'schema-typed/src/DateType'>;
}
declare module 'schema-typed/src/index.js' {
  declare module.exports: $Exports<'schema-typed/src/index'>;
}
declare module 'schema-typed/src/NumberType.js' {
  declare module.exports: $Exports<'schema-typed/src/NumberType'>;
}
declare module 'schema-typed/src/ObjectType.js' {
  declare module.exports: $Exports<'schema-typed/src/ObjectType'>;
}
declare module 'schema-typed/src/Schema.js' {
  declare module.exports: $Exports<'schema-typed/src/Schema'>;
}
declare module 'schema-typed/src/StringType.js' {
  declare module.exports: $Exports<'schema-typed/src/StringType'>;
}
declare module 'schema-typed/src/Type.js' {
  declare module.exports: $Exports<'schema-typed/src/Type'>;
}
