import Head from 'next/head';
import Image from 'next/image';
import { Stack, Button } from 'rsuite';
import styles from '@/styles/About.module.css';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/about.tsx</code>
          </p>

          <Navbar activeKey="about" />
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />

          <Image src="/rsuite.svg" alt="React Suite Logo" width={60} height={60} priority />
        </div>

        <Stack spacing={20}>
          <Button
            appearance="primary"
            size="lg"
            href="https://rsuitejs.com/guide/use-next-pages/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Getting started
          </Button>
          <Button
            size="lg"
            href="https://rsuitejs.com/components/overview/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Components
          </Button>
        </Stack>
      </main>
    </>
  );
}
