// flow-typed signature: a95bccebddd8b99af1884729018e3bae
// flow-typed version: <<STUB>>/babel-preset-rsuite_v^0.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-rsuite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-rsuite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-rsuite/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-rsuite/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-rsuite/lib/index'>;
}
