// flow-typed signature: df5c88b2db2e66d5fac68366bb38db9a
// flow-typed version: <<STUB>>/less-loader_v^4.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'less-loader/dist/createWebpackLessPlugin' {
  declare module.exports: any;
}

declare module 'less-loader/dist/formatLessError' {
  declare module.exports: any;
}

declare module 'less-loader/dist/getOptions' {
  declare module.exports: any;
}

declare module 'less-loader/dist/index' {
  declare module.exports: any;
}

declare module 'less-loader/dist/processResult' {
  declare module.exports: any;
}

declare module 'less-loader/dist/removeSourceMappingUrl' {
  declare module.exports: any;
}

declare module 'less-loader/dist/stringifyLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-loader/dist/cjs.js' {
  declare module.exports: $Exports<'less-loader/dist/cjs'>;
}
declare module 'less-loader/dist/createWebpackLessPlugin.js' {
  declare module.exports: $Exports<'less-loader/dist/createWebpackLessPlugin'>;
}
declare module 'less-loader/dist/formatLessError.js' {
  declare module.exports: $Exports<'less-loader/dist/formatLessError'>;
}
declare module 'less-loader/dist/getOptions.js' {
  declare module.exports: $Exports<'less-loader/dist/getOptions'>;
}
declare module 'less-loader/dist/index.js' {
  declare module.exports: $Exports<'less-loader/dist/index'>;
}
declare module 'less-loader/dist/processResult.js' {
  declare module.exports: $Exports<'less-loader/dist/processResult'>;
}
declare module 'less-loader/dist/removeSourceMappingUrl.js' {
  declare module.exports: $Exports<'less-loader/dist/removeSourceMappingUrl'>;
}
declare module 'less-loader/dist/stringifyLoader.js' {
  declare module.exports: $Exports<'less-loader/dist/stringifyLoader'>;
}
