// flow-typed signature: c2eb0a330705a8528f322941a3694e1d
// flow-typed version: <<STUB>>/webpack-cli_v^3.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/config-yargs' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/convert-argv' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/errorHelpers' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/prepareOptions' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/prompt-command' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/bin/cli.js' {
  declare module.exports: $Exports<'webpack-cli/bin/cli'>;
}
declare module 'webpack-cli/bin/config-yargs.js' {
  declare module.exports: $Exports<'webpack-cli/bin/config-yargs'>;
}
declare module 'webpack-cli/bin/convert-argv.js' {
  declare module.exports: $Exports<'webpack-cli/bin/convert-argv'>;
}
declare module 'webpack-cli/bin/errorHelpers.js' {
  declare module.exports: $Exports<'webpack-cli/bin/errorHelpers'>;
}
declare module 'webpack-cli/bin/prepareOptions.js' {
  declare module.exports: $Exports<'webpack-cli/bin/prepareOptions'>;
}
declare module 'webpack-cli/bin/prompt-command.js' {
  declare module.exports: $Exports<'webpack-cli/bin/prompt-command'>;
}
